-- Seed completo stazioni italiane (fonte gist MarcoBuster).
-- Idempotente su lower(trim(nome)).

INSERT INTO public.stazioni (nome, attiva)
SELECT v.nome, true FROM (VALUES
    ('Ardenno Masino'),
    ('Arena Po'),
    ('Asola'),
    ('Corbetta S. Stefano'),
    ('Cosio Traona'),
    ('Gazzada Schianno Morazzone'),
    ('Gazzo Di Bigarello'),
    ('Ghedi'),
    ('Castel D`Ario'),
    ('Castelleone'),
    ('Castellucchio'),
    ('Castione Andevenno'),
    ('Castronno'),
    ('Cava Carbonara'),
    ('Cava Tigozzi'),
    ('Cavaria Oggiona Jerago'),
    ('Cernusco-Merate'),
    ('Certosa Di Pavia'),
    ('Bressana Argine'),
    ('Bressana Bottarone'),
    ('Broni'),
    ('Chiari'),
    ('Chiavenna'),
    ('Chignolo Po'),
    ('Chiuduno'),
    ('Chiuro'),
    ('Cisano Caprino Bergamasco'),
    ('Civate'),
    ('Coccaglio'),
    ('Codogno'),
    ('Colico'),
    ('Borgoforte'),
    ('Borgolombardo'),
    ('Bozzolo'),
    ('Brenna-Alzate'),
    ('Brescia'),
    ('Candia Lomellina'),
    ('Canneto Sull`Oglio'),
    ('Cantu`- Cermenate'),
    ('Capralba'),
    ('Caravaggio'),
    ('Carimate'),
    ('Carnate Usmate'),
    ('Casalbuttano'),
    ('Casaletto Vaprio'),
    ('Casalmaggiore'),
    ('Casalpusterlengo'),
    ('Casletto-Rogeno'),
    ('Casorate Sempione'),
    ('Cassago-Nibionno-Bulciago'),
    ('Cassano D`Adda'),
    ('Casteggio'),
    ('Abbadia Lariana'),
    ('Abbiategrasso'),
    ('Acquanegra Cremonese'),
    ('Airuno'),
    ('Albate Camerlata'),
    ('Albate-Trecallo'),
    ('Albizzate Solbiate Arno'),
    ('Albuzzano'),
    ('Ambivere Mapello'),
    ('Anzano Del Parco'),
    ('Arcisate'),
    ('Arcore'),
    ('Gambolo`Remondo`'),
    ('Sangiano'),
    ('Sartirana'),
    ('Montirone'),
    ('Monza'),
    ('Monza Sobborghi'),
    ('Morbegno'),
    ('Morengo Bariano'),
    ('Mornago Cimbro'),
    ('Mortara'),
    ('Motteggiana'),
    ('Buttafava'),
    ('Calcio'),
    ('Calde`'),
    ('Calolziocorte Olginate'),
    ('Calusco'),
    ('Calvisano'),
    ('Pavia Porta Garibaldi'),
    ('Remedello Sopra'),
    ('Remedello Sotto'),
    ('Revere'),
    ('Revere Scalo'),
    ('Rho'),
    ('Robecco-Pontevico'),
    ('Gonzaga-Reggiolo'),
    ('Gropello Cairoli'),
    ('Grumello Del Monte'),
    ('Induno Olona'),
    ('Ispra'),
    ('Lambrinia'),
    ('Laveno Mombello'),
    ('Lecco'),
    ('Lecco Maggianico'),
    ('Leggiuno Monvalle'),
    ('Legnano'),
    ('Bagnolo Mella'),
    ('Bellano Tartavelle Terme'),
    ('S.Stefano Lodigiano'),
    ('S. Zeno Folzano'),
    ('S. Zenone Al Lambro'),
    ('Sairano Zinasco'),
    ('Sala Al Barro-Galbiate'),
    ('Samolaco'),
    ('Cologne'),
    ('Como S. Giovanni'),
    ('Secugnago'),
    ('Seregno'),
    ('Seriate'),
    ('Sesto Calende'),
    ('Sesto S. Giovanni'),
    ('Somma Lombardo'),
    ('Sondrio'),
    ('Soresina'),
    ('Stradella'),
    ('Suzzara'),
    ('Taino Angera'),
    ('Talamona'),
    ('Ternate Varano Borghi'),
    ('Terno'),
    ('Ferrera Lomellina'),
    ('Fiumelatte'),
    ('Parabiago'),
    ('Parona Lomellina'),
    ('Pavia'),
    ('Milano Centrale'),
    ('Milano Romolo'),
    ('Seveso'),
    ('Saronno'),
    ('Mariano Comense'),
    ('Asso'),
    ('Cozzo'),
    ('Cremona'),
    ('Cucciago'),
    ('Delebio'),
    ('Desenzano'),
    ('Dorio'),
    ('Oggiono'),
    ('Olcio'),
    ('Olevano'),
    ('Olgiate-Calco-Brivio'),
    ('Olmeneta'),
    ('Orio Litta'),
    ('Osnago'),
    ('Ospedaletto Lodigiano'),
    ('Ospitaletto Mantovano'),
    ('Ostiglia'),
    ('Paderno Robbiate'),
    ('Palazzolo Sull`Oglio'),
    ('Palestro'),
    ('Palidano'),
    ('Torre De` Picenardi'),
    ('Torreberetti'),
    ('Travedona Biandronno'),
    ('Trecella'),
    ('Treviglio'),
    ('Treviglio Ovest'),
    ('Triuggio-Ponte Albiate'),
    ('Tromello'),
    ('Valle Lomellina'),
    ('Lesmo'),
    ('Lierna'),
    ('Lissone-Muggio`'),
    ('Locate Triulzi'),
    ('Rogolo'),
    ('Romano'),
    ('Romanore'),
    ('Rovato'),
    ('Roverbella'),
    ('S.Antonio Mantovano'),
    ('S. Cristina E Bissone'),
    ('Pieve Albignola'),
    ('Piona'),
    ('Pizzighettone'),
    ('Besana'),
    ('Besnate'),
    ('Bianzone'),
    ('Biassono-Lesmo Parco'),
    ('Miradolo Terme'),
    ('Mantova Frassine'),
    ('Moiana'),
    ('Molteno'),
    ('Montello Gorlago'),
    ('Pontida'),
    ('Porto Ceresio'),
    ('Porto Valtravaglia'),
    ('Tavazzano'),
    ('Gallarate'),
    ('Garlasco'),
    ('Gazzo Pieve S. Giacomo'),
    ('Albano S.Alessandro'),
    ('Albonese'),
    ('S. Giacomo Di Teglio'),
    ('S. Giovanni In Croce'),
    ('S.Giuletta'),
    ('S. Giuliano Milanese'),
    ('S.Michele In Bosco'),
    ('Poggio Rusco'),
    ('Belgioioso'),
    ('Besozzo'),
    ('Motta S. Damiano'),
    ('Nicorvo'),
    ('Novate-Mezzola'),
    ('Piadena'),
    ('Pinarolo Po'),
    ('Pioltello Limito'),
    ('Corteolona'),
    ('Costa Masnaga'),
    ('Crema'),
    ('Dervio'),
    ('Desio'),
    ('Varenna Esino'),
    ('Varese'),
    ('Vercurago S.Girolamo'),
    ('Verdello Dalmine'),
    ('Vergiate'),
    ('Verolanuova'),
    ('Viadana Bresciana'),
    ('Vidalengo'),
    ('Vigevano'),
    ('Vignate'),
    ('Villa Di Tirano'),
    ('Villa Raverio'),
    ('Lodi'),
    ('Lonato'),
    ('Luino'),
    ('Lungavilla'),
    ('Macherio-Canonica'),
    ('Macherio Sovico'),
    ('Maleo'),
    ('Mandello Del Lario'),
    ('Manerbio'),
    ('Mantova'),
    ('Marcaria'),
    ('Mede'),
    ('Melegnano'),
    ('Melzo'),
    ('Merone'),
    ('Milano Certosa'),
    ('Milano Greco Pirelli'),
    ('Milano Lambrate'),
    ('Milano Porta Garibaldi'),
    ('Mi.P.Genova'),
    ('Milano Porta Vittoria'),
    ('Milano S. Cristoforo'),
    ('Corsico'),
    ('S. Cassiano Valchiavenna'),
    ('Sannazzaro'),
    ('Gaggiano'),
    ('Lomello'),
    ('Magenta'),
    ('Verceia'),
    ('Malpensa Aeroporto T1'),
    ('Vanzago Pogliano'),
    ('Milano Dateo'),
    ('Bisuschio Viggiu'),
    ('Arcene'),
    ('Levate'),
    ('Stezzano'),
    ('Pozzuolo Martesana'),
    ('Pregnana Milanese'),
    ('Edolo'),
    ('Iseo'),
    ('Bornato - Calino'),
    ('Regoledo'),
    ('Renate-Veduggio'),
    ('Robbio'),
    ('Milano Bovisa Fnm'),
    ('Milano Lancetti'),
    ('Milano Porta Romana'),
    ('Milano Venezia'),
    ('Tresenda-Aprica-Teglio'),
    ('Trezzano S.N.'),
    ('Valmadrera'),
    ('Voghera'),
    ('Sairano'),
    ('Cantu`'),
    ('Carate-Calo`'),
    ('Segrate'),
    ('Busto Arsizio'),
    ('Camnago-Lentate'),
    ('Canegrate'),
    ('Cava Manara'),
    ('Mi P.Gar.Sott.'),
    ('Milano Rogoredo'),
    ('Dubino'),
    ('Tirano'),
    ('Paratico Sarnico'),
    ('Capriolo'),
    ('Barbianello'),
    ('Bergamo'),
    ('Ospitaletto Travagliato'),
    ('S. Pietro Berbenno'),
    ('Villamaggiore'),
    ('Villanova D`Ardenghi'),
    ('Villasanta'),
    ('Villetta Malagnino'),
    ('Visano'),
    ('Vittuone Arluno'),
    ('Zinasco Nuovo'),
    ('Madignano'),
    ('Poggiridenti-Tresivio-Piateda'),
    ('Ponte D`Adda'),
    ('Ponte In Valtellina'),
    ('Ponte S.Marco - Calcinato'),
    ('Ponte S.Pietro'),
    ('Sori'),
    ('Taggia Arma'),
    ('Varazze'),
    ('Ventimiglia'),
    ('Arcola'),
    ('Airole'),
    ('Alassio'),
    ('Albenga'),
    ('Bogliasco'),
    ('Bordighera'),
    ('Borghetto Santo Spirito'),
    ('Borgo Fornari Per Voltaggio'),
    ('Busalla'),
    ('Camogli San Fruttuoso'),
    ('Campoligure Masone'),
    ('Cavi'),
    ('Celle'),
    ('Ceriale'),
    ('Cervo San Bartolomeo'),
    ('Cogoleto'),
    ('Corniglia'),
    ('Deiva Marina'),
    ('Finale Ligure Marina'),
    ('Framura'),
    ('Genova Acquasanta'),
    ('Genova Bolzaneto'),
    ('Genova Borzoli'),
    ('Genova Granara'),
    ('Genova Marittima S. Limbania'),
    ('Genova Nervi'),
    ('Genova Pegli'),
    ('Genova P.Principe'),
    ('Genova Pontedecimo'),
    ('Genova Quarto Dei Mille'),
    ('Genova Rivarolo'),
    ('Genova Sampierdarena'),
    ('Genova Sturla'),
    ('Genova Vesima'),
    ('Genova Voltri'),
    ('Isola Del Cantone'),
    ('La Spezia Centrale'),
    ('Laigueglia'),
    ('Lavagna'),
    ('Levanto'),
    ('Loano'),
    ('Mele'),
    ('Mignanego'),
    ('Moneglia'),
    ('Monterosso'),
    ('Olivetta San Michele'),
    ('Piano Orizzontale Dei Giovi'),
    ('Pietrabissara'),
    ('Pieve Ligure'),
    ('S. Stefano Di Magra'),
    ('Imperia'),
    ('Genova Costa Di Sestri Ponente'),
    ('Genova Quinto Al Mare'),
    ('Genova Via Di Francia'),
    ('Bivio/Pc Arcola'),
    ('Borgio Verezzi'),
    ('Genova P. Principe Sotterranea'),
    ('Cairo Montenotte'),
    ('Cengio'),
    ('Albisola'),
    ('Savona Marittima'),
    ('Spotorno Noli'),
    ('Vallecrosia'),
    ('Vernazza'),
    ('Zoagli'),
    ('Bragno'),
    ('Genova Cornigliano'),
    ('Pietra Ligure'),
    ('S. Margherita Ligure Portofino'),
    ('Genova Pra'),
    ('Genova Sestri Ponente'),
    ('Genova Brignole'),
    ('Pontetto'),
    ('Mulinetti'),
    ('Chiavari'),
    ('Riva Trigoso'),
    ('Bonassola'),
    ('Manarola'),
    ('Ferrania'),
    ('Maschio'),
    ('Vezzano Ligure'),
    ('Ponzano Magra'),
    ('Genova S.Biagio'),
    ('Pont'),
    ('Dego'),
    ('Piana'),
    ('Ca` Di Boschetti'),
    ('Rocchetta Cairo'),
    ('La Spezia Migliarina'),
    ('La Spezia Marittima'),
    ('Sarzana'),
    ('Altare'),
    ('Arenzano'),
    ('Bevera'),
    ('Quiliano Vado'),
    ('Rapallo'),
    ('Recco'),
    ('Riomaggiore'),
    ('Ronco Scr.'),
    ('Rossiglione'),
    ('San Giuseppe Di Cairo'),
    ('Sanremo'),
    ('Santuario'),
    ('Savona'),
    ('Sestri Levante'),
    ('S.Silvestro'),
    ('Settimo'),
    ('Sezzadio'),
    ('Chiusano Cossombrone'),
    ('Collegno'),
    ('Priola'),
    ('Rovasenda'),
    ('S. Ambrogio'),
    ('Isola D`Asti'),
    ('Manta'),
    ('Torre S.Giorgio'),
    ('Tronzano'),
    ('Vaprio D`Agogna'),
    ('Borgo S.Martino'),
    ('Cambiano Santena'),
    ('Villanova'),
    ('Torino Porta Susa'),
    ('Marano Ticino'),
    ('Meina'),
    ('Merana'),
    ('Mercenasco'),
    ('Villastellone'),
    ('Pieve Vergonte'),
    ('Borgo San Dalmazzo'),
    ('Bruzolo'),
    ('Casaleggio'),
    ('Cassine'),
    ('Castelletto Ticino'),
    ('Castello D`Annone'),
    ('Castellazzo Casalcermelli'),
    ('Rovasenda Alta'),
    ('Buronzo'),
    ('Caluso'),
    ('Candia Canavese'),
    ('Cavallermaggiore'),
    ('Cercenasco'),
    ('Roccagrimalda'),
    ('San Giacomo'),
    ('Torino Dora'),
    ('Dormelletto'),
    ('Eca Nasago`'),
    ('Terzo Montabone'),
    ('Torino Lingotto'),
    ('Torino S. Paolo'),
    ('Torino Smistamento Nord'),
    ('Torino Stura'),
    ('Tonco Alfiano'),
    ('Torino P.Nuova'),
    ('Torrazza P.'),
    ('Carbonara Scrivia'),
    ('Alba'),
    ('Asti'),
    ('Bivio Madonna Dell`Olmo'),
    ('Beaulard'),
    ('Morano Sul Po'),
    ('Mussotto'),
    ('Omegna Crusinallo'),
    ('Beura Cardezza'),
    ('Madonna Della Scala'),
    ('Torino Orbassano Fascio Sud'),
    ('Villafranca C.'),
    ('Villafranca P.'),
    ('Vogogna Ossola'),
    ('Monastero Pratavecchi'),
    ('Felizzano'),
    ('Pogliola'),
    ('Pombia'),
    ('Pontecurone'),
    ('Ponti'),
    ('Ponzana'),
    ('Portacomaro'),
    ('Porto Varallo Pombia'),
    ('Solero'),
    ('Strambino'),
    ('Susa'),
    ('Ghislarengo'),
    ('Giarole'),
    ('Magliano Crava Morozzo'),
    ('S. Germano Vercellese'),
    ('S.Giorgio Casale'),
    ('S.Giuliano Piemonte'),
    ('Pocapaglia'),
    ('Baveno'),
    ('Biella Chiavazza'),
    ('Moretta'),
    ('Nibbia'),
    ('Nizza Monferrato'),
    ('None'),
    ('Pc. Meana'),
    ('Pertengo'),
    ('Piedimulera'),
    ('Cuneo Gesso'),
    ('Cureggio'),
    ('Varallo Pombia'),
    ('Varallo Sesia'),
    ('Verbania-Pallanza'),
    ('Vercelli'),
    ('Vergnasco'),
    ('Vernante'),
    ('Verolengo'),
    ('Verzuolo'),
    ('Vespolate'),
    ('Vicoforte San Michele'),
    ('Vigliano Candelo'),
    ('Vigliano D`Asti'),
    ('Vignale'),
    ('Vigone'),
    ('Villadossola'),
    ('Luserna S. Giovanni'),
    ('Maddalene'),
    ('Madonna Del Pilone'),
    ('Margarita'),
    ('Mergozzo'),
    ('Pinerolo Olimpica'),
    ('Crescentino'),
    ('Cressa Fontaneto'),
    ('Cuneo'),
    ('Cunico Scandeluzza'),
    ('Cuzzago'),
    ('Domodossola'),
    ('Domo Ii'),
    ('Dormelletto Paese'),
    ('Dronero'),
    ('Exilles'),
    ('Fara'),
    ('Farigliano'),
    ('Nichelino'),
    ('Niella'),
    ('Novara'),
    ('Nucetto'),
    ('Olcenengo'),
    ('Oleggio'),
    ('Omegna'),
    ('Ornavasso'),
    ('Orta Miasino'),
    ('Oulx Cesana Claviere Sestriere'),
    ('Oviglio'),
    ('Ozzano Monferrato'),
    ('Palazzolo Vercellese'),
    ('Pallanzeno'),
    ('Torre Pellice'),
    ('Trappa'),
    ('Trinita` Bene Vagienna'),
    ('Trino Vercellese'),
    ('Trofarello'),
    ('Valenza'),
    ('Valmadonna'),
    ('Livorno Ferraris'),
    ('Limone'),
    ('Rocchetta Tanaro Cerro'),
    ('Rodallo'),
    ('Romagnano Sesia'),
    ('Rosta'),
    ('S.Anna Robella'),
    ('S. Antonino Di Saluggia'),
    ('S. Antonino Vaie'),
    ('S.Benigno Di Cuneo'),
    ('S. Damiano D`Asti'),
    ('Pessione'),
    ('Pettenasco'),
    ('Pianfei'),
    ('Pievetta'),
    ('Pinerolo'),
    ('Piscina Di Pinerolo'),
    ('Bergamasco'),
    ('Bianze`'),
    ('Bibiana'),
    ('Mombaldone Roccaverano'),
    ('Mombaruzzo'),
    ('Momo'),
    ('Moncalieri'),
    ('Moncalvo'),
    ('Monchiero Dogliani'),
    ('Mondovi`'),
    ('Mongardino'),
    ('Montalto Dora'),
    ('Montanaro'),
    ('Montechiaro D`Asti'),
    ('Montechiaro Denice'),
    ('Montegrosso'),
    ('Fossano'),
    ('Gamalero'),
    ('Moncalieri Sangone'),
    ('Santhia`'),
    ('Penango'),
    ('Monteu Da Po'),
    ('Monticello D`Alba'),
    ('Montiglio Murisengo'),
    ('Narzole'),
    ('Neive'),
    ('Calamandrana'),
    ('Caltignaga'),
    ('Prato Sesia'),
    ('Premosello Chiovenda'),
    ('Quarona'),
    ('Quincinetto'),
    ('Racconigi'),
    ('Robilante'),
    ('Roccaciglie`'),
    ('Roccadebaldi'),
    ('Roccavione'),
    ('Gozzano'),
    ('Gravellona Toce'),
    ('Grignasco'),
    ('Incisa Scapaccino'),
    ('Ivrea'),
    ('Lauriano'),
    ('Lesa'),
    ('Baldichieri'),
    ('Balzola'),
    ('Bandito'),
    ('Bastia Mondovi`'),
    ('Bazzana'),
    ('Beinette'),
    ('Belgirate'),
    ('Bellinzago'),
    ('S. Paolo Solbrito'),
    ('S.Sebastiano Po'),
    ('S.Stefano Belbo'),
    ('S.Vittoria'),
    ('Salbertrand'),
    ('Sale Langhe'),
    ('Saliceto'),
    ('Saluggia'),
    ('Salussola'),
    ('Sandigliano'),
    ('Sanfre`'),
    ('Comignago'),
    ('Condove'),
    ('Savigliano'),
    ('Scalenghe'),
    ('Serralunga Cereseto'),
    ('Serravalle D`Asti'),
    ('Settime Cinaglio Mombarone'),
    ('Settimo Tavagnasco'),
    ('Sillavengo'),
    ('Sizzano'),
    ('Sommariva Bosco'),
    ('Spigno'),
    ('Spinetta'),
    ('Stresa'),
    ('Strevi'),
    ('Suno'),
    ('Lesegno'),
    ('Fontanetto Po'),
    ('Cossato'),
    ('Costigliole (Motta Di)'),
    ('Costigliole D`Asti'),
    ('Costigliole Saluzzo'),
    ('Garbagna'),
    ('Garessio'),
    ('Gattinara'),
    ('Ghemme'),
    ('Castell`Alfero'),
    ('Castelletto Busca'),
    ('Castellino Tanaro'),
    ('Castelnuovo Belbo'),
    ('Castelrosso'),
    ('Cavagnolo Brusasco'),
    ('Centallo'),
    ('Cervignasco'),
    ('Bricherasio'),
    ('Briona'),
    ('Brozolo'),
    ('Bruno'),
    ('Busca'),
    ('Bussoleno'),
    ('Arquata Scrivia'),
    ('Ceva'),
    ('Cherasco'),
    ('Chieri'),
    ('Chiomonte'),
    ('Chivasso'),
    ('Cocconato'),
    ('Avigliana'),
    ('Bivio Castelrosso'),
    ('Bivio Sesia'),
    ('Bagnasco'),
    ('Biella S.Paolo'),
    ('Bistagno'),
    ('Bolzano Novarese'),
    ('Borgo Lavezzaro'),
    ('Borgo Revel'),
    ('Borgo Ticino'),
    ('Borgo Vercelli'),
    ('Borgofranco'),
    ('Borgomanero'),
    ('Borgone'),
    ('Borgoratto'),
    ('Borgosesia'),
    ('Bra'),
    ('Brandizzo'),
    ('Breil Sur Roya'),
    ('Candelo'),
    ('Candiolo'),
    ('Candoglia Ornavasso'),
    ('Canelli'),
    ('Cantalupo'),
    ('Carentino'),
    ('Carisio'),
    ('Carmagnola'),
    ('Carpignano Sesia'),
    ('Carru` Clavesana'),
    ('Casale Monferrato'),
    ('Casale Popolo'),
    ('Castagnole Delle Lanze'),
    ('Prasco Cremolino'),
    ('Predosa'),
    ('Rigoroso'),
    ('Rio Secco'),
    ('Rivalta Scrivia'),
    ('Serravalle Scrivia'),
    ('Stazzano Serravalle'),
    ('Tortona'),
    ('Villalvernia'),
    ('Visone'),
    ('Agliano Castelnuovo Calcea'),
    ('Airasca'),
    ('Alice Belcolle'),
    ('Alpignano'),
    ('Arona'),
    ('Acqui Terme'),
    ('Alessandria'),
    ('Deviatoio Estremo Tortona'),
    ('Cassano Spinola'),
    ('Castelspina Portanova'),
    ('Donna'),
    ('Frugarolo Boscomarengo'),
    ('Molare'),
    ('Novi Ligure'),
    ('Ovada'),
    ('Ovada Nord'),
    ('Pozzolo Formigaro'),
    ('Donnaz'),
    ('Arvier'),
    ('Aosta Viale Europa'),
    ('Avise'),
    ('Villeneuve'),
    ('Pont Saint Martin'),
    ('Nus'),
    ('Verres'),
    ('Derby'),
    ('Sarre'),
    ('Montjovet'),
    ('Morgex'),
    ('Pre` Saint Didier'),
    ('Quart'),
    ('Hone Bard'),
    ('La Salle'),
    ('Saint Pierre'),
    ('Chambave'),
    ('Chatillon Saint Vincent'),
    ('Aosta'),
    ('Aosta Istituto'),
    ('Greccio'),
    ('Grotte S.Stefano'),
    ('Isola Liri'),
    ('Itri'),
    ('La Giustiniana'),
    ('La Storta'),
    ('Lanuvio'),
    ('Latina'),
    ('Bagni Di Tivoli'),
    ('Bassano Romano'),
    ('Salone'),
    ('Sassone'),
    ('Sezze Romano'),
    ('Sora'),
    ('Stimigliano'),
    ('Ferentino-Supino'),
    ('Fiumicino Aeroporto'),
    ('Formia-Gaeta'),
    ('Corchiano'),
    ('Castel Madama'),
    ('Castel S.Angelo'),
    ('Cecchina'),
    ('Ceprano-Falvaterra'),
    ('Ladispoli-Cerveteri'),
    ('Cesano Di Roma'),
    ('Ciampino'),
    ('Cittaducale'),
    ('Civita Castellana'),
    ('Civitavecchia'),
    ('Colle Mattia'),
    ('Collevecchio'),
    ('Bracciano'),
    ('Cancelliera'),
    ('Canetra'),
    ('Capannelle'),
    ('Caprarola'),
    ('Casabianca'),
    ('Cassino'),
    ('Castel Bagnolo Di Orte'),
    ('Acqua Acetosa'),
    ('Albano Laziale'),
    ('Anagni-Fiuggi'),
    ('Anguillara'),
    ('Antrodoco Borgo Velino'),
    ('Antrodoco Centro'),
    ('Anzio'),
    ('Aprilia'),
    ('Arce'),
    ('Arsoli'),
    ('Fabrica Di Roma'),
    ('Deviatoio Estremo Km 2.730-Roma T.Lana'),
    ('Campo Di Carne'),
    ('Anzio Colonia'),
    ('Pavona'),
    ('Terracina'),
    ('Viterbo Porta Fiorentina'),
    ('Zagarolo'),
    ('Fidene'),
    ('Pomezia - S.Palomba'),
    ('Tarquinia'),
    ('Gallese In Teverina'),
    ('La Fiora'),
    ('Mandela-Sambuci'),
    ('S. Eurosia'),
    ('Santa Marinella'),
    ('S.Martino Al Cimino'),
    ('Poggio Fidoni'),
    ('Morolo'),
    ('Cotilia'),
    ('Velletri'),
    ('Vetralla'),
    ('Vico Matrino'),
    ('Vigna Di Valle'),
    ('Villa Bonelli'),
    ('Villa Claudia'),
    ('Lunghezza'),
    ('Maccarese'),
    ('Magliana'),
    ('Manziana-Canale Monterano'),
    ('Marino'),
    ('Minturno'),
    ('Fara Sabina'),
    ('Nuovo Salario'),
    ('Oriolo'),
    ('Orte'),
    ('Padiglione'),
    ('Torre In Pietra-Palidoro'),
    ('Torricola'),
    ('Tre Croci'),
    ('Contigliano'),
    ('Lido Di Lavinio'),
    ('Ronciglione'),
    ('Roviano'),
    ('Nettuno'),
    ('Monte S.Biagio'),
    ('Monterotondo'),
    ('Frascati'),
    ('Frosinone'),
    ('Muratella'),
    ('Civitavecchia Viale Della Vittoria'),
    ('Campoleone'),
    ('Rieti'),
    ('Riofreddo'),
    ('Roma Casilina'),
    ('Roma Monte Mario'),
    ('Gemelli'),
    ('Roma Prenestina'),
    ('Roma S.Filippo Neri'),
    ('Rocca Di Fondi'),
    ('Roccasecca'),
    ('S. Maria Delle Mole'),
    ('Sgurgola'),
    ('Crocicchie'),
    ('Terria'),
    ('Ponte Di Nona'),
    ('Vigna Clara'),
    ('Roma Tuscolana'),
    ('Valmontone'),
    ('Labro Moggio'),
    ('Sorgenti Del Peschiera'),
    ('Montalto Di Castro'),
    ('Civitavecchia M.Ma'),
    ('Santa Severa'),
    ('Roma Aurelia'),
    ('Madonna Del Piano'),
    ('Gallese Bassanello'),
    ('Poggio Mirteto'),
    ('Sette Bagni'),
    ('Piana Bella Montelibretti'),
    ('Sipicciano'),
    ('Montefiascone'),
    ('Viterbo Porta Romana'),
    ('Roma S.Pietro'),
    ('Ponte Galeria'),
    ('Roma Trastevere'),
    ('Roma Ostiense'),
    ('Roma Termini'),
    ('Parco Leonardo'),
    ('Guidonia-Montecelio-S.Angelo'),
    ('Marcellina-Palombara'),
    ('Vicovaro'),
    ('Cisterna Di Latina'),
    ('Priverno Fossanova'),
    ('Fondi - Sperlonga'),
    ('Colleferro-Segni-Paliano'),
    ('Castro-Pofi'),
    ('Quattro Venti'),
    ('Fiera Di Roma'),
    ('Serenissima'),
    ('Pineto'),
    ('Roma S.Lorenzo'),
    ('Roma Tiburtina Piazzale Est'),
    ('Dev.Int. Dd/Av'),
    ('Bivio/P.C. Sgurgola'),
    ('Marechiaro'),
    ('Marina Di Cerveteri'),
    ('Villetta'),
    ('Capranica'),
    ('Castel Gandolfo'),
    ('Ceccano'),
    ('Rocca D`Evandro'),
    ('Isoletta-S.Giovanni I.'),
    ('Roma Tiburtina'),
    ('Tivoli'),
    ('Tor Sapienza'),
    ('Roma Nomentana L.L.'),
    ('Tor Vergata'),
    ('Ipogeo Degli Ottavi'),
    ('Olgiata'),
    ('Appiano'),
    ('Valle Aurelia'),
    ('Arpino'),
    ('Palo Laziale'),
    ('Allerona-Castel Viscardo'),
    ('Alviano'),
    ('Assisi'),
    ('Attigliano'),
    ('Cannara'),
    ('Capodacqua Pieve Fanonica'),
    ('Castiglion Del Lago'),
    ('Scanzano Belfiore'),
    ('Terni'),
    ('Terni Cospea'),
    ('Foligno'),
    ('Pm Panicale Sanfatucchio'),
    ('Passignano Sul Trasimeno'),
    ('Pc Allerona'),
    ('Giuncano'),
    ('Gualdo Tadino'),
    ('Baiano Di Spoleto'),
    ('Baschi-Montecchio'),
    ('Bastia'),
    ('Pc Orvieto'),
    ('Nera Montoro'),
    ('Campello'),
    ('Perugia'),
    ('Perugia Ponte S.Giovanni'),
    ('Monte Melino'),
    ('Fossato Di Vico Gubbio'),
    ('Gaifana'),
    ('Orvieto'),
    ('Ospedalicchio'),
    ('Torricella'),
    ('Trevi'),
    ('Tuoro Sul Trasimeno'),
    ('Magione'),
    ('Ellera Corciano'),
    ('Narni Amelia'),
    ('Nocera Umbra'),
    ('Ponte Parrano Di Nocera Umbra'),
    ('Spoleto'),
    ('S.Giacomo Di Spoleto'),
    ('Valtopina'),
    ('Spello'),
    ('S.Liberato'),
    ('Stroncone'),
    ('Marmore'),
    ('Citta` Della Pieve'),
    ('Fabro-Ficulle'),
    ('Castiglione In Teverina'),
    ('Boiano'),
    ('Bonefro S.Croce'),
    ('Carovilli-Roccasicura'),
    ('Carpinone'),
    ('Casacalenda Guardialfiera'),
    ('Sepino'),
    ('Termoli'),
    ('Guglionesi Portocannone'),
    ('Larino'),
    ('S. Pietro Avellana-Capracotta'),
    ('Campomarino'),
    ('Ripabottoni S.Elia'),
    ('Montenero Petacciato'),
    ('Ururi Rotello'),
    ('Baranello'),
    ('Venafro'),
    ('Sessano Del Molise'),
    ('Vastogirardi'),
    ('Pescolanciano-Chiauci'),
    ('Monteroduni'),
    ('Rocca Ravindola'),
    ('Vinchiaturo'),
    ('Campobasso'),
    ('Cantalupo Del Sannio'),
    ('Campolieto Monacilioni'),
    ('S.Maria Oliveto'),
    ('Capriati Al Volturno'),
    ('Bosco Redole'),
    ('Guardiaregia'),
    ('Matrice Montagano'),
    ('S.Martino In Pensilis'),
    ('Sesto Campano'),
    ('S. Giuliano Piacentino'),
    ('S.Ilario'),
    ('Poggio Renatico'),
    ('Noceto'),
    ('Vergato'),
    ('San Giovanni In Persiceto'),
    ('S.Biagio'),
    ('Roccamurata'),
    ('S.Cassiano'),
    ('Osteria Nuova'),
    ('Villanova Di Reggiolo'),
    ('Bologna Interporto'),
    ('Casteldebole'),
    ('Ozzano Dell''Emilia'),
    ('Casalecchio Garibaldi'),
    ('Funo Centergross'),
    ('Rastignano'),
    ('Pian Di Venola'),
    ('Camposanto'),
    ('Castel S.Pietro Terme'),
    ('Bologna Corticella'),
    ('Rimini Miramare'),
    ('Bologna Ravone'),
    ('Posto Movimento Bolognina'),
    ('Bologna C.Le/Av'),
    ('Reggio Emilia Av'),
    ('S.Lazzaro Di Savena'),
    ('Bologna Fiere'),
    ('Bologna Mazzini'),
    ('Rimini Torre Pedrera'),
    ('S.Martino In Gattara'),
    ('S.Nicolo'''),
    ('Felegara - S.Andrea Bagni'),
    ('Gatteo A Mare'),
    ('Musiano-Pian Di Macina'),
    ('S.Pietro In Casale'),
    ('Salsomaggiore T.'),
    ('Samoggia'),
    ('Sarmato'),
    ('Monticelli D`Ongina'),
    ('Monzuno'),
    ('Cadeo'),
    ('Ravenna'),
    ('Reggio Emilia'),
    ('Rimini Viserba'),
    ('Riccione'),
    ('Rimini'),
    ('Riola'),
    ('Rolo Novi Fabbrico'),
    ('Rottofreno'),
    ('Rubiera'),
    ('Russi'),
    ('S.Agata Sul Santerno'),
    ('Santarcangelo Di Romagna'),
    ('San Benedetto Sambro-Cast.Pepoli'),
    ('Piacenza'),
    ('Berceto'),
    ('Mirandola'),
    ('Posto Mov. Mirandola Ozzano'),
    ('Misano Adriatico'),
    ('Modena'),
    ('Molino Del Pallone'),
    ('Montesanto'),
    ('Galliera'),
    ('Ostia Parmense'),
    ('Ozzano Taro'),
    ('Lido Di Classe-Lido Di Savio'),
    ('Lugo'),
    ('Marzabotto'),
    ('Massalombarda'),
    ('Medesano'),
    ('Mezzani Rondani'),
    ('Mezzano'),
    ('Crevalcore'),
    ('Faenza'),
    ('Barbiano'),
    ('Biagioni Lagacci'),
    ('Pianoro'),
    ('Pioppe Di Salvaro'),
    ('Varignana'),
    ('Vicofertile'),
    ('Villa Cade`'),
    ('Villanova D`Arda'),
    ('Voltana'),
    ('Ponte Della Venturina'),
    ('Pontecchio Marconi'),
    ('Pontelagoscuro'),
    ('Pontenure'),
    ('Porretta  Terme'),
    ('Portomaggiore'),
    ('Gaibanella'),
    ('Gambettola'),
    ('S.Felice Sp'),
    ('S.Giorgio P.'),
    ('Alfonsine'),
    ('Posto Movimento Alseno'),
    ('Argenta'),
    ('Bagnacavallo'),
    ('Bologna Borgo Panigale'),
    ('Bologna S.Ruffillo'),
    ('Bologna C.Le'),
    ('Borghetto Parmense'),
    ('Borgo Val Di Taro'),
    ('Caorso'),
    ('Carbona'),
    ('Carpi'),
    ('Casalecchio Di Reno'),
    ('Castel S.Giovanni'),
    ('Castelbolognese'),
    ('Castelfranco D''Emilia'),
    ('Castelguelfo'),
    ('Castelmaggiore'),
    ('Castelvetro'),
    ('Castione Dei Marchesi'),
    ('Cattolica S.Giovanni Gabicce'),
    ('Cervia-Milano Marittima'),
    ('Brisighella'),
    ('Busseto'),
    ('Cesena'),
    ('Cesenatico'),
    ('Citerna Taro'),
    ('Classe'),
    ('Collecchio'),
    ('Colorno'),
    ('Conselice'),
    ('Sasso Marconi'),
    ('Savignano Sul Rubicone'),
    ('Selva Del Bocchetto'),
    ('Silla'),
    ('Solarolo'),
    ('Soliera Modenese'),
    ('Solignano'),
    ('Strada Casale'),
    ('Pm Tavernelle Emilia'),
    ('Ferrara'),
    ('Fidenza'),
    ('Fiorenzuola'),
    ('Forli`'),
    ('Forlimpopoli'),
    ('Fornovo'),
    ('Parma'),
    ('Glorie'),
    ('Godo'),
    ('Granarolo'),
    ('Grizzana'),
    ('Igea Marina'),
    ('Imola'),
    ('Lama Di Reno'),
    ('Lavezzola'),
    ('Lavino'),
    ('Bellaria'),
    ('Cotignola'),
    ('Avio'),
    ('Bolzano Sud'),
    ('Borghetto'),
    ('Castelbello'),
    ('Casteldarne'),
    ('Bressanone'),
    ('Bronzolo'),
    ('Brunico'),
    ('Chiusa'),
    ('Ciardes'),
    ('Coldrano-Martello'),
    ('Colle Isarco'),
    ('Serravalle'),
    ('Settequerce'),
    ('Silandro'),
    ('Spondigna-Prato Venosta'),
    ('Terlano-Andriano'),
    ('Grigno'),
    ('Laces'),
    ('Laives'),
    ('Lasa'),
    ('Lavis'),
    ('Mori'),
    ('Naturno'),
    ('Caldonazzo'),
    ('Campo Di Trens'),
    ('Roncegno Bagni-Marter'),
    ('S.Cristoforo Al Lago-Ischia'),
    ('Monguelfo Valle Di Casies'),
    ('Ora'),
    ('Oris'),
    ('Valdaora - Anterselva'),
    ('Levico'),
    ('Magre`- Cortaccia'),
    ('Malles Venosta'),
    ('Merano Maia Bassa'),
    ('Mezzocorona'),
    ('Dobbiaco'),
    ('Egna-Termeno'),
    ('Pergine'),
    ('Villabassa - Braies'),
    ('Villazzano'),
    ('Vilpiano-Nalles'),
    ('Ponte D`Adige'),
    ('Ponte Gardena'),
    ('Sluderno-Glorenza'),
    ('Strigno'),
    ('Ala'),
    ('Tezze Di Grigno'),
    ('Plaus'),
    ('Marlengo'),
    ('Borgo Valsugana Est'),
    ('Calceranica'),
    ('Vandoies'),
    ('Trento S.Chiara'),
    ('Rio Di Pusteria'),
    ('Salorno'),
    ('Lana-Postal'),
    ('Vipiteno'),
    ('P.M.Vat'),
    ('Tarvisio Boscoverde'),
    ('Bivio Cargnacco'),
    ('Montereale Valcellina'),
    ('S.Stefano Udinese'),
    ('S.Giovanni Di Casarsa'),
    ('Meduno'),
    ('Confine Italo/Sloveno'),
    ('San Giorgio Di Nogaro'),
    ('Strassoldo'),
    ('Artegna'),
    ('Aurisina'),
    ('Aviano'),
    ('Bivio D`Aurisina'),
    ('Bivio San Polo'),
    ('Capriva'),
    ('Carnia'),
    ('Casarsa'),
    ('Cervignano A.G.'),
    ('Budoia Polcenigo'),
    ('Codroipo'),
    ('Sevegliano'),
    ('Sistiana'),
    ('Tarcento'),
    ('Fontanafredda'),
    ('Forgaria Bagni Anduins'),
    ('Cordovado Sesto'),
    ('Cornino'),
    ('Gemona Del Friuli'),
    ('Gorizia Centrale'),
    ('Grignano'),
    ('Latisana Lignano B.'),
    ('Basiliano'),
    ('S.Vito Al Tagliamento'),
    ('Sacile'),
    ('Sacile San Liberale'),
    ('Sagrado'),
    ('Mossa'),
    ('Muzzana Del Turgnano'),
    ('Buttrio'),
    ('Redipuglia'),
    ('Risano'),
    ('Ronchi Dei Legionari Nord'),
    ('Ronchi Dei Legionari Sud'),
    ('Pinzano'),
    ('Monfalcone'),
    ('Osoppo'),
    ('Palazzolo Dello Stella'),
    ('Palmanova'),
    ('Torviscosa'),
    ('Travesio'),
    ('Trieste Centrale'),
    ('Trieste Campo Marzio'),
    ('Trieste Aquilinia'),
    ('Udine'),
    ('Udine Parco'),
    ('Ugovizza Valbruna'),
    ('Lumignacco'),
    ('Majano'),
    ('Cusano'),
    ('Fanna - Cavasso'),
    ('Bagnaria Arsa'),
    ('Cormons'),
    ('Venzone'),
    ('Villa Opicina'),
    ('Villa Vicentina'),
    ('Pontebba'),
    ('Pordenone'),
    ('Maniago'),
    ('Manzano'),
    ('S.Giovanni Al Natisone'),
    ('S.Maria La Longa'),
    ('Fabriano Ca` Maiano'),
    ('Marino Del Tronto Folignano'),
    ('Albacina'),
    ('Ancona'),
    ('Ancona Marittima'),
    ('Ascoli Piceno'),
    ('Castelraimondo Camerino'),
    ('Sassoferrato Arcevia'),
    ('Serra S.Quirico'),
    ('Spinetoli Colli'),
    ('Pantiere Di Castelbellino'),
    ('Pedaso'),
    ('Pergola'),
    ('Morrovalle Monte S.Giusto'),
    ('S.Claudio'),
    ('Pesaro'),
    ('Montemarciano'),
    ('Monteprandone'),
    ('Monterosso Marche'),
    ('Offida Castel Di Lama'),
    ('Osimo Castelfidardo'),
    ('Palombina'),
    ('Loreto'),
    ('Macerata'),
    ('Maltignano Del Tronto'),
    ('Marotta Mondolfo'),
    ('Marzocca'),
    ('Matelica'),
    ('Cupramarittima'),
    ('Fabriano'),
    ('Fano'),
    ('Potenza Picena Montelupone'),
    ('Varano'),
    ('Pollenza'),
    ('Porto Recanati'),
    ('Porto S. Giorgio Fermo'),
    ('Grottammare'),
    ('Jesi'),
    ('Urbisaglia Sforzacosta'),
    ('Falconara Stadio'),
    ('Cerreto D`Esi'),
    ('Ancona Torrette'),
    ('Macerata Fontescodella'),
    ('Castelferretti'),
    ('Bellisio Solfare'),
    ('Melano Marischio'),
    ('Senigallia'),
    ('Falconara Marittima'),
    ('Chiaravalle'),
    ('Montecarotto Castelbellino'),
    ('Castelplanio Cupramontana'),
    ('Genga S.Vittore Terme'),
    ('S.Severino Marche'),
    ('Tolentino'),
    ('Corridonia Mogliano'),
    ('Montecosaro'),
    ('Gagliole'),
    ('Civitanova Marche'),
    ('Porto S. Elpidio'),
    ('S.Benedetto Del Tronto'),
    ('Monsampolo Del Tronto'),
    ('S.Filippo'),
    ('Villabartolomea'),
    ('Villafranca Di Verona'),
    ('Villaverla Montecchio'),
    ('Anconetta'),
    ('Ve Asseggiano'),
    ('Polesella'),
    ('Ponte Di Brenta'),
    ('Portogruaro Caorle'),
    ('Stazione Per L`Alpago'),
    ('Grisignano Di Zocco'),
    ('Istrana'),
    ('Alano Fener Valdobbiadene'),
    ('S. Dona` Di Piave'),
    ('S.Elena - Este'),
    ('S.Giorgio Delle Pertiche'),
    ('S.Giustina Cesio'),
    ('S.Martino Buon Albergo'),
    ('S.Martino Di Lupari'),
    ('S.Nazario'),
    ('Fae`Fortogna'),
    ('Thiene'),
    ('Olmi Spercenigo'),
    ('S.Biagio Di Callalta'),
    ('Fagare'),
    ('Ponte Di Piave'),
    ('Oderzo'),
    ('Gorgo Al Monticano'),
    ('Motta Di Livenza'),
    ('Pramaggiore'),
    ('Annone Veneto'),
    ('San Bonifacio'),
    ('Posto Comunicazione Dolce`'),
    ('Vittorio Veneto'),
    ('Carmignano Di Brenta'),
    ('Caldiero'),
    ('Campodarsego'),
    ('Ceregnano'),
    ('Trebaseleghe'),
    ('Venezia Porto Marghera'),
    ('Spinea'),
    ('S.Trovaso'),
    ('Venezia Marittima'),
    ('Gr Sc Mestre St'),
    ('Primolano'),
    ('Quarto D`Altino'),
    ('S.Marino'),
    ('Conegliano'),
    ('Ponte Nelle Alpi Polpet'),
    ('Quero Vas'),
    ('Resana'),
    ('Lendinara'),
    ('Verona Porta Vescovo'),
    ('Preganziol'),
    ('Roncanova Di Gazzo Ver.'),
    ('Rosa`'),
    ('Rosolina'),
    ('Rossano Veneto'),
    ('Rovigo'),
    ('S.Croce Del Lago'),
    ('Peschiera Del Garda'),
    ('Pianzano'),
    ('Piombino Dese'),
    ('Belluno'),
    ('Bevilacqua'),
    ('Mira Mirano'),
    ('Mogliano Veneto'),
    ('Monselice'),
    ('Montagnana'),
    ('Montebello'),
    ('Montebelluna'),
    ('Fossalta Di Piave'),
    ('Fossalta Di Portogruaro'),
    ('Fratta'),
    ('Fratte Centro'),
    ('Gaggio'),
    ('Galliera Veneta Tombolo'),
    ('Noale Scorze`'),
    ('Nogara'),
    ('Nove'),
    ('Orsago'),
    ('Ospedaletto Euganeo'),
    ('Ospitale Di Cadore'),
    ('Padova'),
    ('Paese'),
    ('Paese Castagnole'),
    ('Trevignano Signoressa'),
    ('Treviso C.'),
    ('Levada'),
    ('Lisiera'),
    ('Lison'),
    ('Longarone Zoldo'),
    ('Lonigo'),
    ('Loreo'),
    ('Maerne Di Martellago'),
    ('Marano'),
    ('Meolo'),
    ('Mestrino'),
    ('Dolo'),
    ('Domegliara'),
    ('Dossobuono'),
    ('Dueville'),
    ('Este'),
    ('Fanzolo'),
    ('Occhiobello'),
    ('Venezia Carpenedo'),
    ('Venezia Mestre'),
    ('Venezia Santa Lucia'),
    ('Verona Ca` Di David'),
    ('Verona Porta Nuova'),
    ('Vicenza'),
    ('Vigodarzere'),
    ('Vigonza Pianiga'),
    ('Villa Del Conte'),
    ('Abano Terme'),
    ('Adria'),
    ('Albaredo'),
    ('Altavilla Tavernelle'),
    ('Arqua`'),
    ('Badia Polesine'),
    ('Bonferraro'),
    ('Boschi S.Anna'),
    ('Bovolone'),
    ('P.C.Canaro'),
    ('Carpane`Valstagna'),
    ('Cassola'),
    ('Castello Di Godego'),
    ('Castagnaro'),
    ('Castelfranco Veneto'),
    ('Castelnuovo'),
    ('Cavanella D`Adige'),
    ('Cavanella Po'),
    ('Cavazzale'),
    ('Ceggia'),
    ('Cerea'),
    ('Busche Lentiai Mel'),
    ('Chioggia'),
    ('Cismon Del Grappa'),
    ('Cittadella'),
    ('Schio'),
    ('Sedico Bribano'),
    ('Soffratta'),
    ('Solagna'),
    ('Spresiano'),
    ('Stanghella'),
    ('Susegana'),
    ('Teglio Veneto'),
    ('Terme Euganee-Abano-Montegr.'),
    ('Feltre'),
    ('Fontaniva'),
    ('Cornuda'),
    ('Costa'),
    ('Isola Della Scala'),
    ('Lama'),
    ('Lancenigo'),
    ('Legnago'),
    ('Lerino'),
    ('Baricetta'),
    ('Bassano Del Grappa'),
    ('Battaglia Terme'),
    ('S.Pietro In Gu`'),
    ('S. Stino Di Livenza'),
    ('Saletto'),
    ('Salzano Robegano'),
    ('Sanguinetto'),
    ('Pederobba Cavaso Possagno'),
    ('Perarolo Di Cadore'),
    ('Peri'),
    ('Mozzecane'),
    ('Buttapietra'),
    ('Calalzo Pieve Cadore Cortina'),
    ('Camposampiero'),
    ('Postioma'),
    ('Pove Del Grappa Campese'),
    ('Le Piagge'),
    ('Cambiano'),
    ('Castellina Marittima'),
    ('Castelvecchio Pascoli'),
    ('Castiglioncello'),
    ('Certaldo'),
    ('Firenze Statuto'),
    ('Castiglion Fiorentino'),
    ('Chiusi C.T.'),
    ('Chiarone'),
    ('Asciano Monte Oliveto Maggiore'),
    ('Binario S.Marco Vecchio'),
    ('Ripafratta'),
    ('S.Miniato Fucecchio'),
    ('S. Pietro A Vico'),
    ('S.Romano Montopoli S.Croce'),
    ('Serravalle Pistoiese'),
    ('Rignano Sull`Arno Reggello'),
    ('Firenze S.M.N.'),
    ('Forte Dei Marmi Serravezza Q.'),
    ('Il Cionfo Bin. Le Cure'),
    ('Pontassieve'),
    ('Ponte A Elsa'),
    ('Ponte A Moriano'),
    ('Ponte A Tressa'),
    ('Ponte Ginori'),
    ('Ponticino'),
    ('Pontremoli'),
    ('Popolano'),
    ('Porcari'),
    ('Giuncarico'),
    ('Incisa'),
    ('Indicatore'),
    ('S.Donnino Badia'),
    ('S.Ellero'),
    ('S.Frediano A Settimo'),
    ('S.Giovanni Valdarno'),
    ('Santa Luce'),
    ('Poggibonsi'),
    ('Poggio - Careggine - Vagli'),
    ('Equi Terme'),
    ('Terontola Cortona'),
    ('Terrarossa - Tresana'),
    ('Tombolo'),
    ('Il Cionfo Bin. Salviati'),
    ('Pian Del Mugnone'),
    ('Fiesole Caldine'),
    ('Mimmole'),
    ('Montorsoli'),
    ('Cercina'),
    ('Fontebuona'),
    ('Vaglia'),
    ('Campomigliaio'),
    ('Scopeti'),
    ('Albinia'),
    ('Arbia'),
    ('San Momme`'),
    ('Vernio Montepiano Cantagallo'),
    ('Castagneto Carducci'),
    ('Ghivizzano - Coreglia'),
    ('Massarosa Bozzano'),
    ('S.Giuliano Terme'),
    ('Tassignano'),
    ('Borgo A Buggiano'),
    ('Montecatini Terme'),
    ('Firenze Rifredi'),
    ('Prato Porta Al Serraglio'),
    ('Pontedera Casciana Terme'),
    ('Montelupo Capraia'),
    ('Livorno Centrale'),
    ('Populonia'),
    ('Fiorentina Di Piombino'),
    ('Castelfiorentino'),
    ('Castelnuovo Berardenga'),
    ('S.Giovanni D`Asso'),
    ('Roccastrada'),
    ('Torrita Di Siena'),
    ('Serre Di Rapolano'),
    ('Siena Zona Industriale'),
    ('Monteroni D`Arbia'),
    ('Buonconvento'),
    ('Fi Rovezzano'),
    ('Aulla Lunigiana'),
    ('Volterra Saline - Pomarance'),
    ('Campiglia Marittima'),
    ('Camporgiano'),
    ('Piombino Binari Porto Vecchio'),
    ('Pracchia'),
    ('Pratignone'),
    ('Prato Centrale'),
    ('Quercianella'),
    ('Rapolano Terme'),
    ('Rigoli'),
    ('Rigomagno'),
    ('Riparbella'),
    ('Ronta'),
    ('Rosignano'),
    ('Rufina'),
    ('Piazza Al Serchio'),
    ('Pietrasanta'),
    ('Piombino'),
    ('Piombino Binari Mare'),
    ('Pisa Binari Aeroporto'),
    ('Pisa Centrale'),
    ('Pisa San Rossore'),
    ('Pistoia'),
    ('Montale Agliana'),
    ('Montallese'),
    ('Monte Antico'),
    ('Montecarlo San Salvatore'),
    ('Montecatini Centro'),
    ('Montepescali'),
    ('Montepulciano'),
    ('Fosciandora - Ceserana'),
    ('Nozzano'),
    ('Orbetello'),
    ('Orciano'),
    ('Pallerone'),
    ('Torre Del Lago Puccini'),
    ('Torrenieri'),
    ('Vada'),
    ('Vaiano'),
    ('Valdibrana'),
    ('Contea Londa'),
    ('Lucca'),
    ('Marradi'),
    ('Massa Centro'),
    ('Minucciano - Pieve - Casola'),
    ('Prato Borgonuovo'),
    ('Dicomano'),
    ('Diecimo - Pescaglia'),
    ('Empoli'),
    ('Barga Gallicano'),
    ('Navacchio'),
    ('Pescia'),
    ('Piteccio'),
    ('Viareggio'),
    ('Vicarello'),
    ('Vicchio'),
    ('Vignale Riotorto'),
    ('Villafranca - Bagnone'),
    ('Villetta S. Romano'),
    ('Zambra'),
    ('S.Piero A Sieve'),
    ('Fauglia - Lorenzana'),
    ('Alberese'),
    ('Altopascio'),
    ('Antignano'),
    ('Arezzo'),
    ('Asciano'),
    ('Aulla'),
    ('Bivio Mortellini'),
    ('P.M. Badesse'),
    ('Biforco'),
    ('Bolgheri'),
    ('Borgo A Mozzano'),
    ('Borgo S. Lorenzo'),
    ('Borgo S.L.Rimorelli'),
    ('Camucia Cortona'),
    ('Capalbio'),
    ('Carrara Avenza'),
    ('Cascina'),
    ('Casino Di Terra'),
    ('Castagno'),
    ('Castellina Ch'),
    ('Castelnuovo Di Garfagnana'),
    ('Cecina'),
    ('Bucine'),
    ('Civitella Paganico'),
    ('Colle Val D`Elsa'),
    ('Collesalvetti'),
    ('Compiobbi'),
    ('Scarlino'),
    ('Scorcetoli'),
    ('Sesto Fiorentino'),
    ('Sieci'),
    ('Siena'),
    ('Signa'),
    ('Sinalunga'),
    ('Sticciano'),
    ('Talamone'),
    ('Firenze Campo Marte'),
    ('Firenze Cascine'),
    ('Firenze Castello'),
    ('Figline Valdarno'),
    ('Filattiera'),
    ('Fivizzano - Gassano'),
    ('Fivizzano Rometta - Soliera'),
    ('Follonica'),
    ('Fornaci Di Barga'),
    ('Panicaglia'),
    ('Corbezzi'),
    ('Gavorrano'),
    ('Gragnola'),
    ('Granaiolo'),
    ('Grosseto'),
    ('Il Neto'),
    ('Laterina'),
    ('Bagni Di Lucca'),
    ('S. Vincenzo'),
    ('Montevarchi Terranuova'),
    ('Doppio Bivio Montuolo'),
    ('Monzone-M.Dei Banchi-Isolano'),
    ('Murlo'),
    ('Calenzano'),
    ('Camaiore Lido Capezzano'),
    ('Guardia Mangano Santa Venerina'),
    ('Catania Centrale'),
    ('Catania Acquicella'),
    ('Agnone Di S.'),
    ('Brucoli'),
    ('Motta Camastra'),
    ('Caltanissetta Xirbi'),
    ('Dirillo'),
    ('Vittoria'),
    ('Donnafugata'),
    ('Modica'),
    ('S.Teresa Longarini'),
    ('Gela-Anic'),
    ('Carini Torre Ciachea'),
    ('Catenanuova'),
    ('Orsa'),
    ('Cefalu`'),
    ('Mili Marina'),
    ('Ponte S.Stefano'),
    ('Villabate'),
    ('Priolo Soprano'),
    ('Ragusa Ibla'),
    ('Serradifalco'),
    ('Pozzallo'),
    ('Sciara A.'),
    ('Siracusa'),
    ('Sparagogna'),
    ('Licata'),
    ('Castelluccio Siculo'),
    ('Torregrotta'),
    ('Tommaso Natale'),
    ('Piraineto'),
    ('Gole Di Alcantara'),
    ('Punta Raisi'),
    ('Leonforte-Pirato'),
    ('S.Flavia'),
    ('Acquedolci-S.Fratello'),
    ('San Giorgio'),
    ('Oliveri Tindari'),
    ('Palermo Brancaccio'),
    ('S.Nicola Di Mazara'),
    ('Castelvetrano'),
    ('Gallitello'),
    ('Cinisi Terrasini'),
    ('Cardillo Zen'),
    ('Roccapalumba-Alia'),
    ('Mimiani-S.Cataldo'),
    ('Motta Santa Anastasia'),
    ('Militello'),
    ('Targia'),
    ('Graniti'),
    ('Mojo-Alcantara Malvagna'),
    ('Racalmuto'),
    ('Favarotta'),
    ('Ragusa'),
    ('S.Paolo'),
    ('Campobello Ravanusa'),
    ('Palermo Sampolo'),
    ('Federico'),
    ('Palermo Marittima'),
    ('Caltanissetta Centrale'),
    ('Castronovo Di Sicilia'),
    ('Altavilla M.'),
    ('Fiumetorto'),
    ('Pollina'),
    ('Santo Stefano Di Camastra'),
    ('S.Agata M.'),
    ('Brolo Ficarra'),
    ('Novara Montalbano Furnari'),
    ('Barcellona'),
    ('Milazzo'),
    ('Villafranca Tirrena'),
    ('Mozia-Birgi'),
    ('Terrenove'),
    ('Mazara Del Vallo'),
    ('Salemi Gibellina'),
    ('Castellammare Del Golfo'),
    ('Palazzo Reale-Orleans'),
    ('Segesta Tempio'),
    ('Fulgatore'),
    ('Campofranco'),
    ('Comitini'),
    ('Agrigento Bassa'),
    ('Valledolmo'),
    ('Dittaino'),
    ('Grammichele'),
    ('Mineo'),
    ('Palagonia'),
    ('Messina Centrale'),
    ('Giampilieri'),
    ('Scaletta Zanclea'),
    ('Roccalumera Mandanici'),
    ('Santa Teresa Di Riva'),
    ('Mascali'),
    ('Campofelice'),
    ('Priolo Melilli'),
    ('Raddusa Agira'),
    ('Randazzo'),
    ('Rometta Messinese'),
    ('Rosolini'),
    ('S.Alessio Siculo Forza D`Agro`'),
    ('S.Cataldo'),
    ('Petrosino Strasatti'),
    ('Bicocca'),
    ('Montemaggiore'),
    ('Francavilla'),
    ('Francia'),
    ('Furci'),
    ('Gaggi'),
    ('Galati'),
    ('Niscemi'),
    ('Nizza Di Sicilia'),
    ('Noto'),
    ('Palermo Notarbartolo'),
    ('Pace Del Mela'),
    ('Paceco'),
    ('Pachino'),
    ('Palermo Centrale'),
    ('Torre Del Lauro'),
    ('Trabia'),
    ('Trapani'),
    ('Trappeto'),
    ('Tremestieri'),
    ('Tusa'),
    ('Vallelunga'),
    ('Contesse'),
    ('Letojanni'),
    ('Libertinia'),
    ('Marausa'),
    ('Marcatobianco'),
    ('Marianopoli'),
    ('Marsala'),
    ('Marzamemi'),
    ('Megara G.'),
    ('Messina Marittima'),
    ('Milo'),
    ('Delia'),
    ('Enna'),
    ('Falconara'),
    ('Falcone'),
    ('Piana Del Signore'),
    ('Venetico'),
    ('Vespri'),
    ('Villalba'),
    ('Villarosa'),
    ('Vituso'),
    ('Vizzini'),
    ('Zappulla'),
    ('Portiere Stella'),
    ('Porto Empedocle'),
    ('Spadafora'),
    ('Taormina'),
    ('Gerbini'),
    ('Isola Delle Femmine'),
    ('S.Filippo-S.Lucia'),
    ('S.Lorenzo Colli'),
    ('San Marco D`Alunzio T.'),
    ('San Martino Piana'),
    ('Acate'),
    ('Acireale'),
    ('Acquaviva'),
    ('Agrigento Centrale'),
    ('Alcamo'),
    ('Alcamo Diramazione'),
    ('Alcantara'),
    ('Ali` Terme'),
    ('Aragona Caldare'),
    ('Augusta'),
    ('Avola'),
    ('Bagheria'),
    ('Canicatti`'),
    ('Cannizzaro'),
    ('Capaci'),
    ('Capo D`Orlando-Naso'),
    ('Carini'),
    ('Caronia'),
    ('Carruba'),
    ('Cassibile'),
    ('Castelbuono'),
    ('Casteldaccia'),
    ('Castiglione Di Sicilia'),
    ('Castrofilippo'),
    ('Cerda'),
    ('Bruca'),
    ('Buonfornello'),
    ('Butera'),
    ('Comiso'),
    ('Comitini Zolfare'),
    ('Scicli'),
    ('Scordia'),
    ('Sferro'),
    ('Siracusa M.'),
    ('Spagnuola'),
    ('Terme Vigliatore'),
    ('Termini Imerese'),
    ('Fiera'),
    ('Fildidonna'),
    ('Fiumefreddo Di Sicilia'),
    ('Partinico'),
    ('Passomartino'),
    ('Patti-San Piero Patti'),
    ('Gela'),
    ('Genisi'),
    ('Giachery'),
    ('Giarre Riposto'),
    ('Giojosa Marea'),
    ('Grotte'),
    ('Imera'),
    ('Ispica'),
    ('Lascari'),
    ('Lentini'),
    ('Lentini Diramazione'),
    ('Lercara Bassa'),
    ('Balestrate'),
    ('S.Nicola T.'),
    ('S.Oliva'),
    ('Sampieri'),
    ('Calatabiano'),
    ('Calatafimi'),
    ('Caltagirone'),
    ('Cammarata S.Giovanni Gemini'),
    ('Campobello Di Mazara'),
    ('Policoro Tursi'),
    ('Albano Di Lucania'),
    ('Acquafredda'),
    ('Maratea'),
    ('Marconia'),
    ('Metaponto'),
    ('Filiano'),
    ('Forenza'),
    ('Bella Muro'),
    ('Salandra'),
    ('Monticchio'),
    ('Calciano'),
    ('Campomaggiore'),
    ('Potenza Superiore'),
    ('Rionero Atella Ripacandita'),
    ('Picerno'),
    ('Pietragalla'),
    ('Pisticci'),
    ('Trivigno'),
    ('Bernalda'),
    ('Balvano R.'),
    ('Tiera'),
    ('Marina Di Maratea'),
    ('Monteverde'),
    ('Barile'),
    ('Potenza Centrale'),
    ('Baragiano'),
    ('Scanzano J. Montalbano J.'),
    ('Nova Siri Rotondella'),
    ('Rapone Ruvo S.Fele'),
    ('Pisciolo'),
    ('Tito'),
    ('Lagonegro'),
    ('Melfi'),
    ('Castel Lagopesole'),
    ('Avigliano Lucania'),
    ('Leonessa'),
    ('Possidente'),
    ('S. Nicola Di Melfi'),
    ('Venosa - Maschito'),
    ('Palazzo S.Gervasio - Montemil.'),
    ('Vaglio Basilicata'),
    ('Brindisi Di Montagna'),
    ('Grassano'),
    ('Ferrandina'),
    ('Calitri Pescopagano'),
    ('S.Tommaso Del Piano'),
    ('Gravina In Puglia'),
    ('Palagiano Mottola'),
    ('Monteiasi'),
    ('Margherita Di Sav./Ofantino'),
    ('Minervino Murge'),
    ('Brindisi Marittima'),
    ('Candida'),
    ('Castellaneta Marina'),
    ('Troia Castelluccio Sauri'),
    ('Chieuti Serracapriola'),
    ('Amendola'),
    ('Frattarolo'),
    ('Manfredonia'),
    ('Trinitapoli S.Ferdin. Di P.'),
    ('Fasano'),
    ('Carovigno'),
    ('S.Vito Dei Normanni'),
    ('Squinzano'),
    ('Ordona'),
    ('Rocchetta S.Ant.Lac.'),
    ('Canne Della Battaglia'),
    ('Acquaviva Delle Fonti'),
    ('Francavilla Fontana'),
    ('Bari S. Spirito'),
    ('Rignano Garganico'),
    ('Grottaglie'),
    ('Altamura'),
    ('Apricena'),
    ('Ascoli Satriano'),
    ('Bari Palese Macchie'),
    ('Bari S.Andrea'),
    ('Bari S.Giorgio'),
    ('Bisceglie'),
    ('Bitetto Palo Del Colle'),
    ('Bovino Deliceto'),
    ('Candela'),
    ('Canosa Di Puglia'),
    ('Casal Sabini'),
    ('Cerignola'),
    ('Cervaro'),
    ('Brindisi'),
    ('Cisternino'),
    ('Siponto'),
    ('Spinazzola'),
    ('Taranto'),
    ('Gioia Del Colle'),
    ('Incoronata'),
    ('Latiano'),
    ('Lecce'),
    ('Barletta'),
    ('Bellavista'),
    ('S. Pietro Vernotico'),
    ('San Severo'),
    ('Sannicandro Di Bari'),
    ('Santuario Incoronata'),
    ('Santeramo'),
    ('Posto Movimento Ripalta'),
    ('Modugno Citta`'),
    ('Molfetta'),
    ('Monopoli'),
    ('Oria'),
    ('Ortanova'),
    ('Ostuni'),
    ('Palagianello'),
    ('Palagiano Chiatona'),
    ('Trani'),
    ('Trepuzzi'),
    ('Tuturano'),
    ('Massafra'),
    ('Mesagne'),
    ('Cozze'),
    ('Egnazia'),
    ('Bari Parco Nord'),
    ('Bari Torre A Mare'),
    ('Villa Castelli'),
    ('Polignano A Mare'),
    ('Ponte Albanito'),
    ('Ginosa'),
    ('Giovinazzo'),
    ('Grumo Appula'),
    ('Poggio Imperiale'),
    ('Poggiorsini'),
    ('Bari Parco Sud'),
    ('Mola Di Bari'),
    ('Nasisi'),
    ('Foggia'),
    ('Praja Ajeta Tortora'),
    ('Reggio Di Calabria Catona'),
    ('Riace'),
    ('Rocca Imperiale'),
    ('Saline Di Reggio'),
    ('Scilla'),
    ('Simeri Crichi'),
    ('Tarsia'),
    ('Reggio Calabria Lido'),
    ('R.C.Aeroporto'),
    ('Fiumefreddo Bruzio'),
    ('Francavilla Angitola F.'),
    ('Fuscaldo'),
    ('Gabella Grande'),
    ('Gizzeria Lido'),
    ('Grisolia S.Maria'),
    ('Guardavalle'),
    ('Guardia Piemontese Terme'),
    ('Lamezia Terme Nicastro'),
    ('Lamezia Terme Sambiase'),
    ('Locri'),
    ('Longobardi'),
    ('Marcellina Verbicaro Orsomarso'),
    ('Marcellinara'),
    ('Marina Di San Lorenzo'),
    ('Mirto Crosia'),
    ('Monasterace Stilo'),
    ('Mongrassano Cervicati'),
    ('Montepaone - Montauro'),
    ('Motta San Giovanni Lazzaro'),
    ('Nicotera'),
    ('Nocera Tirinese'),
    ('Palizzi'),
    ('Palmi'),
    ('Paola'),
    ('Pietrapaola'),
    ('Scalea S.Domenica Talao'),
    ('Lamezia Terme Centrale'),
    ('Cutro'),
    ('Gioia Tauro'),
    ('S.Lucido Marina'),
    ('Sibari'),
    ('S.Andrea Dell`Jonio'),
    ('Montalto Rose'),
    ('Catanzaro'),
    ('Villa S.Giovanni Mare'),
    ('Joppolo'),
    ('Bagnara'),
    ('Villa S.G.Cannitello'),
    ('Reggio Di Calabria Gallico'),
    ('Santa Domenica'),
    ('Mileto'),
    ('Monte Giordano'),
    ('Villapiana Torre Cerchiara'),
    ('Corigliano Calabro'),
    ('Mandatoriccio Campana'),
    ('Isola Capo Rizzuto'),
    ('Catanzaro Lido'),
    ('Soverato'),
    ('S.Caterina Dell`Jonio'),
    ('Gioiosa Jonica'),
    ('Brancaleone'),
    ('Bova Marina'),
    ('Melito Di Porto Salvo'),
    ('Reggio Di Calabria S.Gregorio'),
    ('Spezzano Albanese Terme'),
    ('S.Marco Roggiano'),
    ('Castiglione Cosentino'),
    ('Feroleto Antica Pianopoli'),
    ('Bivio Pantani'),
    ('Villa San Giovanni'),
    ('Parghelia'),
    ('Pizzo'),
    ('Reggio Calabria Centrale'),
    ('Reggio Calabria Marittima'),
    ('Reggio Di Calabria Pellaro'),
    ('Ricadi'),
    ('Roccabernarda'),
    ('Roccella Jonica'),
    ('Rosarno'),
    ('Roseto Capo Spulico'),
    ('Rossano'),
    ('S.Nicola Arcella'),
    ('S.Pietro A Maida'),
    ('San Leonardo Di Cutro'),
    ('Sangineto'),
    ('Santa Maria Di Catanzaro'),
    ('Sellia Marina'),
    ('Settingiano'),
    ('Siderno'),
    ('Squillace'),
    ('Strongoli'),
    ('Thurio'),
    ('Torano Lattarico'),
    ('Torre Melissa'),
    ('Trebisacce'),
    ('Tropea'),
    ('Vibo Marina'),
    ('Vibo Valenzia Pizzo'),
    ('Villa S. Giovanni Bolano'),
    ('Villapiana Lido'),
    ('Zambrone'),
    ('Acquappesa'),
    ('Acri Bisignano Luzzi'),
    ('Africo Nuovo'),
    ('Amantea'),
    ('Amendolara Oriolo'),
    ('Ardore'),
    ('Badolato'),
    ('Belmonte Calabro'),
    ('Belvedere Marittimo'),
    ('Bianco'),
    ('Bivio Settimo'),
    ('Botricello'),
    ('Bovalino'),
    ('Briatico'),
    ('Calopezzati'),
    ('Campora S.Giov. Serra Aiello'),
    ('Capo Bonifati'),
    ('Capo Spartivento'),
    ('Cariati'),
    ('Cassano All`Ionio'),
    ('Caulonia'),
    ('Cetraro'),
    ('Cirella Majera`'),
    ('Ciro'''),
    ('Condofuri'),
    ('Cosenza'),
    ('Cropani'),
    ('Crotone'),
    ('Crucoli'),
    ('Diamante Buonvicino'),
    ('Eccellente'),
    ('Falerna'),
    ('Favazzina'),
    ('Ferruzzano'),
    ('Pagani'),
    ('Contursi Terme'),
    ('Bivio S.Lucia (Na)'),
    ('Bagnoli Agnano Terme'),
    ('Albanova'),
    ('Valle Di Maddaloni'),
    ('Galdo'),
    ('Montesano Buonabitacolo'),
    ('Sassano Teggiano'),
    ('Casalnuovo'),
    ('Buccino S.'),
    ('Paestum'),
    ('Torchiara'),
    ('Napoli Piazza Leopardi'),
    ('Piazza Cavour'),
    ('Vairano'),
    ('Sparanise'),
    ('Maddaloni Inferiore'),
    ('Gricignano'),
    ('Amorosi Melizzano'),
    ('Ponte Casalduni'),
    ('Paduli'),
    ('Montecalvo Buonalbergo Casalb.'),
    ('Telese Cerreto'),
    ('Fragneto Monforte'),
    ('Pescosannita Fragneto L`Abate'),
    ('Pietrelcina'),
    ('Benevento Porta Rufina'),
    ('Altavilla Irpina'),
    ('Tufo'),
    ('Prata Pratola'),
    ('Fratte Villa Comunale'),
    ('Montemiletto'),
    ('Castelvetere'),
    ('Morra De Sanctis Teora'),
    ('Sanzano Occhino'),
    ('Palma S.Gennaro'),
    ('Castel S.Giorgio Roccapiemonte'),
    ('Valle Di Mercato S.Severino'),
    ('Napoli S.Giov.Barra'),
    ('Portici- Ercolano'),
    ('Vietri Sul Mare'),
    ('Pontecagnano'),
    ('Campagna Serre Persano'),
    ('Sicignano Degli Alburni'),
    ('Atena'),
    ('Rutino'),
    ('Vallo Della Luc. Castelnuovo'),
    ('S.Giuseppe Vesuviano'),
    ('Romagnano V.'),
    ('S.Michele Di Serino'),
    ('Serino'),
    ('Taurasi'),
    ('Giugliano Qualiano'),
    ('Mercatello'),
    ('Arbostella'),
    ('S.Angelo Dei Lombardi'),
    ('S.Antimo S.Arpino'),
    ('S.Croce Del Sannio'),
    ('Pianerottolo Di Ariano'),
    ('Pietrarsa'),
    ('Benevento'),
    ('Montefalcione'),
    ('Montefredane'),
    ('Montella'),
    ('Montemarano'),
    ('Frasso T. Dugenta'),
    ('Frattamaggiore'),
    ('Fratte'),
    ('Nocera Inferiore'),
    ('Nocera Inferiore Mercato'),
    ('Nocera Superiore'),
    ('Nola'),
    ('Ottaviano'),
    ('Torre Annunziata Centrale'),
    ('Torre Annunziata Citta'''),
    ('Torre Del Greco'),
    ('Lioni'),
    ('Lioni Valle Delle Viti'),
    ('Maddaloni Superiore'),
    ('Marcianise'),
    ('Marigliano'),
    ('Mignano Di Monte Lungo'),
    ('Eboli'),
    ('Baronissi'),
    ('Morcone'),
    ('Napoli Campi Flegrei'),
    ('Napoli Piazza Garibaldi'),
    ('Pellezzano'),
    ('Villa Literno'),
    ('Vitulano Foglianise'),
    ('Auletta'),
    ('Padula'),
    ('Petina'),
    ('Polla'),
    ('Sala Consilina'),
    ('Pompei'),
    ('Pontelandolfo'),
    ('Solofra'),
    ('Spartimento Di Scisciano'),
    ('S.Lorenzo Maggiore'),
    ('S.Marcellino Frignano'),
    ('S.Maria Capua Vetere'),
    ('S.Maria La Bruna'),
    ('Terzigno'),
    ('Tora Presenzano'),
    ('Agropoli Castellabate'),
    ('Capaccio Roccadaspide'),
    ('Pisciotta Palinuro'),
    ('Torre Orsaia'),
    ('Montaguto Panni'),
    ('Montecorvino'),
    ('Nusco'),
    ('Falciano Mondragone Car.'),
    ('Pignataro Maggiore'),
    ('Benevento Arco Traiano'),
    ('Luogosano'),
    ('Mercato San Severino'),
    ('San Mauro La Bruca'),
    ('San Nicola Varco Di Eboli'),
    ('Sapri'),
    ('Acerra'),
    ('Angri'),
    ('Apice S.Arcangelo Bonito'),
    ('Aquilonia'),
    ('Ariano Irpino'),
    ('Avellino'),
    ('Aversa'),
    ('Boccia Al Mauro'),
    ('Borgo'),
    ('Boscoreale'),
    ('Cancello'),
    ('Cancello Arnone'),
    ('Capua'),
    ('Casalbuono'),
    ('Caserta'),
    ('Casoria'),
    ('Cassano Irpino'),
    ('Castelfranci'),
    ('Castellammare Di Stabia'),
    ('Cava Dei Tirreni'),
    ('Cavalleggeri Aosta'),
    ('Ascea'),
    ('Battipaglia'),
    ('Celle Bulgheria Roccagloriosa'),
    ('Centola'),
    ('Omignano Salento'),
    ('Policastro Bussentino'),
    ('Cese'),
    ('Chianche Ceppaloni'),
    ('Codola'),
    ('Savignano Greci'),
    ('Scafati'),
    ('Sessa Aurunca R.'),
    ('Solopaca'),
    ('Teano'),
    ('Fisciano'),
    ('Paternopoli'),
    ('Corsano'),
    ('Gragnano'),
    ('Lanzara Fimiani'),
    ('Lavorate'),
    ('Bagnoli Irpino'),
    ('Salerno'),
    ('Salza Irpina'),
    ('Sarno'),
    ('Montoro Forino'),
    ('Montoro Superiore'),
    ('Montorsi'),
    ('Napoli Gianturco'),
    ('Napoli Mergellina'),
    ('Napoli Montesanto'),
    ('Piazza Amedeo'),
    ('Napoli Centrale'),
    ('Campo Di Nusco'),
    ('Campolattaro'),
    ('Pozzuoli Solfatara'),
    ('Quarto Di Marano'),
    ('Recale'),
    ('Reviglione Di Somma Vesuviana'),
    ('Riardo'),
    ('Pettorano Sul Gizio'),
    ('Fossacesia'),
    ('Civita D`Antino-Morino'),
    ('S.Vincenzo V.R.'),
    ('Sulmona-Introdacqua'),
    ('Rivisondoli-Pescocostanzo'),
    ('Castel Di Sangro'),
    ('Scerne Di Pineto'),
    ('Bugnara'),
    ('Bussi'),
    ('Campo Di Giove'),
    ('Pratola Peligna Superiore'),
    ('Vigliano D`Abruzzo'),
    ('Tione Degli Abruzzi'),
    ('Popoli Vittorito'),
    ('Tortoreto Lido'),
    ('Pineto Atri'),
    ('Teramo'),
    ('Castellalto Canzano'),
    ('Sante Marie'),
    ('Carrito-Ortona'),
    ('Campo Di Giove-Monte Maiella'),
    ('Cocullo'),
    ('Alanno'),
    ('Alba Adriatica Nereto Contr.'),
    ('Alfedena-Scontrone'),
    ('Anversa-Villalago-Scanno'),
    ('Avezzano'),
    ('Capistrello'),
    ('Cappelle-Magliano'),
    ('Carsoli'),
    ('Casalbordino Pollutri'),
    ('Celano-Ovindoli'),
    ('Cerchio'),
    ('Chieti'),
    ('Civitella Roveto'),
    ('Colli Di Monte Bove'),
    ('Sassa Tornimparte'),
    ('Scafa S.Valentino Caramanico T'),
    ('Scurcola Marsicana'),
    ('Sella Di Corno'),
    ('Fontecchio'),
    ('Giulianova'),
    ('L`Aquila'),
    ('S.Vito Lanciano'),
    ('Montesilvano'),
    ('Mosciano S. Angelo'),
    ('Pratola Peligna'),
    ('Prezza'),
    ('Raiano'),
    ('Roccaraso'),
    ('Roseto Degli Abruzzi'),
    ('Pescara'),
    ('Pescara Porta Nuova'),
    ('Pescina'),
    ('Pescocanale'),
    ('Piano D`Orta Bolognano'),
    ('Molina Castel Vecchio Subaqueo'),
    ('Francavilla Al Mare'),
    ('Notaresco'),
    ('Oricola-Pereto'),
    ('Ortona'),
    ('Paganica'),
    ('Palena'),
    ('Torre Dei Passeri'),
    ('Manoppello'),
    ('Pescara S. Marco'),
    ('Fossacesia - Torino Di Sangro'),
    ('Cupone'),
    ('Fagnano Campana'),
    ('Balsorano'),
    ('Beffi'),
    ('Bellante Ripattone'),
    ('Vasto S.Salvo'),
    ('Villa San Sebastiano'),
    ('Porto Di Vasto'),
    ('Silvi'),
    ('Sulmona'),
    ('Tagliacozzo'),
    ('Goriano Sicoli'),
    ('Acciano'),
    ('S.Demetrio De` Vestini'),
    ('Tocco Castiglione'),
    ('Tollo Canosa Sannita'),
    ('Torino Di Sangro Paglieta'),
    ('Assemini'),
    ('Bonorva'),
    ('Borore'),
    ('Caniga'),
    ('Chirialza'),
    ('Cixerri'),
    ('Scala Di Giocca'),
    ('Siliqua'),
    ('Solarussa'),
    ('Su Canale'),
    ('Iglesias'),
    ('Barbusi'),
    ('Bauladu Milis'),
    ('Sant`Orsola'),
    ('Samassi Serrenti'),
    ('Sanluri Stato'),
    ('Sant`Anna'),
    ('Monti Telti'),
    ('Cagliari'),
    ('Cagliari Elmas'),
    ('Cala Sabina'),
    ('Campomela'),
    ('Berchidda'),
    ('Monte Arcau'),
    ('Golfo Aranci Marittima'),
    ('Golfo Aranci'),
    ('Olbia'),
    ('Oristano'),
    ('Oschiri'),
    ('Pabillonis'),
    ('Macomer'),
    ('Decimomannu'),
    ('Musei'),
    ('Ploaghe'),
    ('Villamassargia Domusnovas'),
    ('Villasor'),
    ('Porto Torres'),
    ('Abbasanta'),
    ('San Gavino'),
    ('Enas'),
    ('Torralba'),
    ('Porto Torres Marittima'),
    ('S.Giorgio Di Sassari'),
    ('Madonna Di Castro'),
    ('Paulilatino'),
    ('Villaspeciosa Uta'),
    ('San Giovanni'),
    ('Sassari'),
    ('Tissi Usini'),
    ('Ardara'),
    ('Marinella'),
    ('Ozieri Fraigas'),
    ('Ozieri Chilivani'),
    ('Mores Ittireddu'),
    ('Giave'),
    ('Marrubiu Terralba Arborea'),
    ('Serramanna Nuraminis'),
    ('Rudalza'),
    ('Olbia Marittima Isola Bianca'),
    ('Carbonia Serbariu'),
    ('Uras Mogoro'),
    ('Borgo Valsugana Centro'),
    ('Rovereto'),
    ('Trento'),
    ('Bolzano'),
    ('Fortezza'),
    ('S.Candido'),
    ('Merano'),
    ('Anzola'),
    ('Bari Centrale'),
    ('Gaggio Porta Est'),
    ('Lolli'),
    ('Pieve Emanuele'),
    ('Busa Di Vigonza'),
    ('Marconi'),
    ('Bari Torre Quetta'),
    ('Rescaldina'),
    ('Castellanza'),
    ('Busto Arsizio Nord'),
    ('Ferno-Lonate Pozzolo'),
    ('Arechi'),
    ('Torrione'),
    ('Pastena'),
    ('Piedimonte-V.S.L.-Aquino'),
    ('Labico'),
    ('Fontanarosa'),
    ('Torino Rebaudengo Fossata'),
    ('Fontane Bianche'),
    ('Elmas Aeroporto'),
    ('Bologna San Vitale'),
    ('Torrile S. Polo'),
    ('Catania Ognina'),
    ('Picanello'),
    ('Catania Europa'),
    ('Sferracavallo'),
    ('Ems-La Malfa'),
    ('Guadagna'),
    ('Brennero'),
    ('Gargazzone'),
    ('Casanova Kaiserau'),
    ('La Rustica Uir'),
    ('La Rustica Citta'''),
    ('Palmiro Togliatti'),
    ('Lastra A Signa'),
    ('Canistro'),
    ('Santopadre'),
    ('Fontana Liri Inferiore'),
    ('Colfelice'),
    ('Venezia Mestre Ospedale'),
    ('Miramare'),
    ('Ottavia'),
    ('Roma Balduina'),
    ('Quattro Ville'),
    ('Rovigliano'),
    ('Duomo Via Vernieri'),
    ('Borgonuovo'),
    ('Calderara-Bargellino'),
    ('Colonna Galleria'),
    ('Bergamo Ospedale'),
    ('Pescara Tribunale'),
    ('S.Donato Milanese'),
    ('Milano Repubblica'),
    ('Milano Quarto Oggiaro'),
    ('Novate Milanese'),
    ('Bollate Centro'),
    ('Bollate Nord'),
    ('Garbagnate Parco Delle Groane'),
    ('Garbagnate Milanese'),
    ('Cesate'),
    ('Caronno Pertusella'),
    ('Saronno Sud'),
    ('Milano Villapizzone'),
    ('Milano Forlanini'),
    ('Rho Fiera Milano'),
    ('Chieti-Mad.D.P.'),
    ('Gavignano'),
    ('Stabio'),
    ('Cantello Gaggiolo'),
    ('Chiasso'),
    ('Catania Aer. Fontanarossa'),
    ('Fiumara Gazzi'),
    ('Ponte Schiavo'),
    ('San Paolo'),
    ('Diano'),
    ('Andora'),
    ('Trieste Airport'),
    ('Modugno'),
    ('Bari Villaggio Del Lavoratore'),
    ('Castellaneta'),
    ('Porto D`Ascoli'),
    ('Martinsicuro'),
    ('Levata'),
    ('Borgochiesanuova'),
    ('Formigine'),
    ('Policlinico'),
    ('Modena Piazza Manzoni'),
    ('Fornaci'),
    ('Baggiovara Ospedale'),
    ('Baggiovara'),
    ('Casinalbo'),
    ('Camerano Aspio'),
    ('Trento S.Bartolameo'),
    ('Povo'),
    ('Vignola'),
    ('Ceretolo'),
    ('Casalecchio Palasport'),
    ('Riate'),
    ('Pilastrino'),
    ('Zola Centro'),
    ('Zola Chiesa'),
    ('Ponte Ronca'),
    ('Via Lunga'),
    ('Crespellano'),
    ('Muffa'),
    ('Bazzano'),
    ('Savignano Mulino'),
    ('Savignano Comune'),
    ('Bari Zona Industriale'),
    ('Crespino Del Lamone'),
    ('Fognano'),
    ('Ficarazzi'),
    ('Roccella'),
    ('Potenza Macchia Romana'),
    ('Albairate'),
    ('Bardonecchia'),
    ('Grugliasco'),
    ('Riminifiera'),
    ('Tricesimo - San Pelagio'),
    ('Reggio Di Calabria Omeca'),
    ('Cesano Boscone'),
    ('Milano Tibaldi - Bocconi'),
    ('Seveso Baruccana'),
    ('Cesano Maderno'),
    ('Ceriano Laghetto-Solaro'),
    ('Rocca Di Corno'),
    ('L`Aquila Campo Di Pile'),
    ('Reggio Di Calabria Archi'),
    ('Reggio Di Calabria Pentimele'),
    ('Reggio Di Calabria S.Caterina'),
    ('S. Gennaro'),
    ('Trecate'),
    ('Provaglio - Timoline'),
    ('Borgonato - Adro'),
    ('Passirano'),
    ('Paderno'),
    ('Castegnato'),
    ('Borgo S. Giovanni'),
    ('Potenza Univ.'),
    ('Perugia Silvestrini'),
    ('Nepezzano-Piano D''Accio'),
    ('Camnago Lentate'),
    ('Milano Bovisa'),
    ('Brunico Nord'),
    ('Perca'),
    ('S.Lorenzo'),
    ('Napoli Afragola'),
    ('Brindisi Ricerca'),
    ('Brindisi-Perrino'),
    ('S.Patrizio'),
    ('Monsampolo Del T'),
    ('Colli Del Tronto'),
    ('Acquamela'),
    ('Salerno Irno'),
    ('Compre S.Vincenzo'),
    ('Ridotti-Collepiano'),
    ('Roccavivi'),
    ('Morrea-Castronovo-Rendinara'),
    ('Pantanella'),
    ('Novate M.Se'),
    ('M N Cadorna'),
    ('Como Nord Lago'),
    ('Varese Nord'),
    ('Como Nord Borghi'),
    ('Milano Nord Domodossola'),
    ('Rovello Porro'),
    ('Rovellasca - Manera'),
    ('Lomazzo'),
    ('Caslino Al Piano'),
    ('Cadorago'),
    ('Fino Mornasco'),
    ('Portichetto - Luisago'),
    ('Grandate - Breccia'),
    ('Como Nord Camerlata'),
    ('Cabiate'),
    ('Meda'),
    ('Bovisio M. - Mombello'),
    ('Varedo'),
    ('Palazzolo M.Se'),
    ('Paderno Dugnano'),
    ('Cormano-Cusano Milanino'),
    ('M.N. Bruzzano'),
    ('M.N. Affori'),
    ('M.N. Quarto Oggiaro'),
    ('Garbagnate Parco Groane'),
    ('Garbagnate M.Se'),
    ('Caronno - Pertusella'),
    ('Malnate'),
    ('Vedano'),
    ('Venegono Sup. - Castiglio'),
    ('Venegono Inf.'),
    ('Tradate'),
    ('Abbiate Guazzone'),
    ('Locate V. - Carbonate'),
    ('Mozzate'),
    ('Cislago'),
    ('Gerenzano - Turate'),
    ('Rivarolo'),
    ('Franciosa'),
    ('Prata Camportaccio'),
    ('Olbia Terranova'),
    ('Barruccana'),
    ('Ceriano Laghetto'),
    ('Canzo'),
    ('Caslino D''Erba'),
    ('Pontelambro - Castelmarte'),
    ('Erba'),
    ('Lambrugo - Lurago'),
    ('Inverigo'),
    ('Arosio'),
    ('Carugo - Giussano'),
    ('Pistoia Ovest'),
    ('L''Aquila Sassa N.S.I.'),
    ('Pisogne'),
    ('Breno'),
    ('Sulzano'),
    ('Sale Marasino'),
    ('Marone - Zone'),
    ('Piancamuno - Gratacasolo'),
    ('Darfo - Corna'),
    ('Boario Terme'),
    ('Pian Di Borno'),
    ('Cogno - Esine'),
    ('Cividate - Malegno'),
    ('Ciano D''Enza'),
    ('Via Fanti - Tribunale'),
    ('Reggio S.Stefano'),
    ('Reggio All''Angelo'),
    ('Cavriago'),
    ('Cavriago S.Nicolo'''),
    ('C.C.9 Bivio Parco'),
    ('Barco'),
    ('Fossa'),
    ('Bibbiano'),
    ('Corniano'),
    ('Piazzola'),
    ('S.Polo D''Enza'),
    ('Ciano Via Tedaldo Da Canossa'),
    ('Guastalla'),
    ('Reggio S.Croce'),
    ('Reggio Stadio Giglio'),
    ('Reggio Mediopadana'),
    ('Pratofontana'),
    ('Bagnolo In Piano'),
    ('Bagnolo Soave'),
    ('Pieve Rossa'),
    ('S.Tomaso'),
    ('Vezzola'),
    ('S.Giovanni (Fer)'),
    ('Novellara'),
    ('S.Bernardino'),
    ('S.Giacomo (Fsc)'),
    ('Isernia'),
    ('Roveri'),
    ('Consandolo'),
    ('Molinella'),
    ('Guarda'),
    ('Mezzolara'),
    ('Budrio Centro'),
    ('Budrio'),
    ('Castenaso'),
    ('Castenaso Stellina'),
    ('Ca'' Dell''Orbo'),
    ('Codisotto'),
    ('Luzzara'),
    ('Tagliata'),
    ('Gualtieri'),
    ('Pieve Saliceto'),
    ('Boretto'),
    ('Brescello Viadana'),
    ('Pilzone'),
    ('Vello'),
    ('Toline'),
    ('Reggio Di Calabria Bocale'),
    ('Perugia Universita'''),
    ('Perugia Capitini'),
    ('Laveno'),
    ('Cittiglio'),
    ('Gemonio'),
    ('Cocquio - Trevisago'),
    ('Gavirate'),
    ('Barasso - Comerio'),
    ('Morosolo - Casciago'),
    ('Varese Casbeno'),
    ('Sipicciano S.Nicola'),
    ('Barberino Val D`Elsa'),
    ('Luni'),
    ('Cagliari S.Gilla'),
    ('Assemini Carmine'),
    ('Assemini S. Lucia'),
    ('Aielli'),
    ('Collarmele'),
    ('Vaio Ospedale'),
    ('Vievola'),
    ('Tende'),
    ('La Brigue'),
    ('St.Dalmas De Tende'),
    ('Fontan Saorge'),
    ('Milano Affori'),
    ('Milano Bruzzano Parco Nord'),
    ('Palazzolo Milanese'),
    ('Bovisio Masciago'),
    ('Macerata Universita'''),
    ('Codigoro'),
    ('Ferrara Boschetto'),
    ('Ferrara-Cona Ospedale'),
    ('Cona F. C.'),
    ('Quartesana'),
    ('Masi Torello'),
    ('Tresigallo - Correggi'),
    ('Rovereto - S.V. - Medelana'),
    ('Dogato'),
    ('Ostellato'),
    ('Migliarino'),
    ('Valcesura'),
    ('Migliaro'),
    ('Massafiscaglia'),
    ('Vigarano Pieve'),
    ('Bondeno'),
    ('Stellata Ficarolo'),
    ('Felonica Po'),
    ('Sermide'),
    ('Magnacavallo'),
    ('Schivenoglia'),
    ('Quistello'),
    ('San Benedetto Po'),
    ('Pegognaga'),
    ('Coronella'),
    ('Novara Nord'),
    ('Gavirate Verbano'),
    ('Vanzaghello - Magnago'),
    ('Castano Primo'),
    ('Turbigo'),
    ('Galliate'),
    ('Modane'),
    ('Busto Arsizio Rfi'),
    ('Ferno Lonate Pozzolo'),
    ('Sassuolo Radici'),
    ('Pratissolo'),
    ('Scandiano'),
    ('Chiozza'),
    ('Casalgrande'),
    ('Dinazzano'),
    ('Villalunga'),
    ('Veggia'),
    ('Pm Bosco'),
    ('Traccia'),
    ('Citta'' Del Ragazzo'),
    ('Bibbiano Via Monti'),
    ('S.Lazzaro'),
    ('Pratovecchio Stia'),
    ('Spinet.V.S.Pio X'),
    ('L''Aquila S. Gregorio'),
    ('Bazzano (Aq)'),
    ('Piove Di Sacco'),
    ('Bivio S.Antonello'),
    ('Milano Cadorna'),
    ('Milano Domodossola'),
    ('Gerenzano-Turate'),
    ('Locate Varesino-Carbonate'),
    ('Venegono Inferiore'),
    ('Venegono Superiore-Castiglione O.'),
    ('Vedano Olona'),
    ('Morosolo Casciago'),
    ('Barasso-Comerio'),
    ('Cocquio Trevisago'),
    ('Laveno Mombello Lago'),
    ('Rovellasca-Manera'),
    ('Portichetto-Luisago'),
    ('Grandate-Breccia'),
    ('Como Camerlata'),
    ('Como Borghi'),
    ('Como Lago'),
    ('Brescia Borgo San Giovanni'),
    ('Paderno Franciacorta'),
    ('Bornato-Calino'),
    ('Borgonato-Adro'),
    ('Provaglio-Timoline'),
    ('Marone-Zone'),
    ('Carugo-Giussano'),
    ('Lambrugo-Lurago D''Erba'),
    ('Pontelambro-Castelmarte'),
    ('Vanzaghello-Magnago'),
    ('Mendrisio'),
    ('Cividate-Malegno'),
    ('Cogno-Esine'),
    ('Darfo-Corna'),
    ('Pian Camuno-Gratacasolo'),
    ('Biasca'),
    ('Castione'),
    ('Bellinzona'),
    ('Giubiasco'),
    ('Lamone-Cadempino'),
    ('Lugano'),
    ('Capolago-Riva S.Vitale'),
    ('Mendrisio S. Martino'),
    ('Taverne-Torricella'),
    ('Mezzovico'),
    ('Rivera-Bironico'),
    ('Locarno'),
    ('Tenero'),
    ('Gordola'),
    ('Riazzino'),
    ('Cadenazzo'),
    ('S.Antonino'),
    ('Ponte Ticino'),
    ('Galliate Parco Del Ticino'),
    ('Groane'),
    ('Ceriano Laghetto Groane'),
    ('Malpensa Aeroporto T2')
) AS v(nome)
WHERE NOT EXISTS (
  SELECT 1 FROM public.stazioni s
  WHERE lower(trim(s.nome)) = lower(trim(v.nome))
);
