alter table public.vestiario_fabbisogno_annuo_config
drop constraint if exists vestiario_fabbisogno_annuo_config_tshirt_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_pantalone_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_felpa_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_giacca_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_gilet_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_scarpe_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_guanti_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_tshirt_estivo_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_pantalone_estivo_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_scarpe_estivo_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_felpa_invernale_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_giacca_invernale_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_gilet_invernale_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_guanti_invernale_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_pantalone_invernale_check,
drop constraint if exists vestiario_fabbisogno_annuo_config_scarpe_invernale_check;

alter table public.vestiario_fabbisogno_annuo_config
add constraint vestiario_fabbisogno_annuo_config_tshirt_check check (tshirt >= 0),
add constraint vestiario_fabbisogno_annuo_config_pantalone_check check (pantalone >= 0),
add constraint vestiario_fabbisogno_annuo_config_felpa_check check (felpa >= 0),
add constraint vestiario_fabbisogno_annuo_config_giacca_check check (giacca >= 0),
add constraint vestiario_fabbisogno_annuo_config_gilet_check check (gilet >= 0),
add constraint vestiario_fabbisogno_annuo_config_scarpe_check check (scarpe >= 0),
add constraint vestiario_fabbisogno_annuo_config_guanti_check check (guanti >= 0),
add constraint vestiario_fabbisogno_annuo_config_tshirt_estivo_check check (tshirt_estivo >= 0),
add constraint vestiario_fabbisogno_annuo_config_pantalone_estivo_check check (pantalone_estivo >= 0),
add constraint vestiario_fabbisogno_annuo_config_scarpe_estivo_check check (scarpe_estivo >= 0),
add constraint vestiario_fabbisogno_annuo_config_felpa_invernale_check check (felpa_invernale >= 0),
add constraint vestiario_fabbisogno_annuo_config_giacca_invernale_check check (giacca_invernale >= 0),
add constraint vestiario_fabbisogno_annuo_config_gilet_invernale_check check (gilet_invernale >= 0),
add constraint vestiario_fabbisogno_annuo_config_guanti_invernale_check check (guanti_invernale >= 0),
add constraint vestiario_fabbisogno_annuo_config_pantalone_invernale_check check (pantalone_invernale >= 0),
add constraint vestiario_fabbisogno_annuo_config_scarpe_invernale_check check (scarpe_invernale >= 0);
