alter table public.logistica_mdo_ferroviari
  add column if not exists dispositivo_shuntaggio_check boolean not null default false,
  add column if not exists dispositivo_shuntaggio_checked_at timestamptz,
  add column if not exists dispositivo_shuntaggio_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists lanterna_bilux_check boolean not null default false,
  add column if not exists lanterna_bilux_checked_at timestamptz,
  add column if not exists lanterna_bilux_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists fanali_coda_check boolean not null default false,
  add column if not exists fanali_coda_checked_at timestamptz,
  add column if not exists fanali_coda_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists tabella_coda_check boolean not null default false,
  add column if not exists tabella_coda_checked_at timestamptz,
  add column if not exists tabella_coda_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists torcia_fiamma_rossa_check boolean not null default false,
  add column if not exists torcia_fiamma_rossa_checked_at timestamptz,
  add column if not exists torcia_fiamma_rossa_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists bandiera_rossa_asta_check boolean not null default false,
  add column if not exists bandiera_rossa_asta_checked_at timestamptz,
  add column if not exists bandiera_rossa_asta_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists scarpe_fermacarro_check boolean not null default false,
  add column if not exists scarpe_fermacarro_checked_at timestamptz,
  add column if not exists scarpe_fermacarro_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists chiave_tripla_snodata_check boolean not null default false,
  add column if not exists chiave_tripla_snodata_checked_at timestamptz,
  add column if not exists chiave_tripla_snodata_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists barra_traino_check boolean not null default false,
  add column if not exists barra_traino_checked_at timestamptz,
  add column if not exists barra_traino_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists vaschetta_raccolta_liquidi_check boolean not null default false,
  add column if not exists vaschetta_raccolta_liquidi_checked_at timestamptz,
  add column if not exists vaschetta_raccolta_liquidi_checked_by_user_uuid uuid references public.users(id_uuid) on delete set null;
