alter table public.logistica_mdo_ferroviari
  add column if not exists dispositivo_shuntaggio_richiesta_sostituzione boolean not null default false,
  add column if not exists dispositivo_shuntaggio_richiesta_sostituzione_at timestamptz,
  add column if not exists dispositivo_shuntaggio_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists lanterna_bilux_richiesta_sostituzione boolean not null default false,
  add column if not exists lanterna_bilux_richiesta_sostituzione_at timestamptz,
  add column if not exists lanterna_bilux_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists fanali_coda_richiesta_sostituzione boolean not null default false,
  add column if not exists fanali_coda_richiesta_sostituzione_at timestamptz,
  add column if not exists fanali_coda_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists tabella_coda_richiesta_sostituzione boolean not null default false,
  add column if not exists tabella_coda_richiesta_sostituzione_at timestamptz,
  add column if not exists tabella_coda_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists torcia_fiamma_rossa_richiesta_sostituzione boolean not null default false,
  add column if not exists torcia_fiamma_rossa_richiesta_sostituzione_at timestamptz,
  add column if not exists torcia_fiamma_rossa_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists bandiera_rossa_asta_richiesta_sostituzione boolean not null default false,
  add column if not exists bandiera_rossa_asta_richiesta_sostituzione_at timestamptz,
  add column if not exists bandiera_rossa_asta_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists scarpe_fermacarro_richiesta_sostituzione boolean not null default false,
  add column if not exists scarpe_fermacarro_richiesta_sostituzione_at timestamptz,
  add column if not exists scarpe_fermacarro_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists chiave_tripla_snodata_richiesta_sostituzione boolean not null default false,
  add column if not exists chiave_tripla_snodata_richiesta_sostituzione_at timestamptz,
  add column if not exists chiave_tripla_snodata_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists barra_traino_richiesta_sostituzione boolean not null default false,
  add column if not exists barra_traino_richiesta_sostituzione_at timestamptz,
  add column if not exists barra_traino_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists vaschetta_raccolta_liquidi_richiesta_sostituzione boolean not null default false,
  add column if not exists vaschetta_raccolta_liquidi_richiesta_sostituzione_at timestamptz,
  add column if not exists vaschetta_raccolta_liquidi_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists doc_carte_circolazione_richiesta_sostituzione boolean not null default false,
  add column if not exists doc_carte_circolazione_richiesta_sostituzione_at timestamptz,
  add column if not exists doc_carte_circolazione_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists doc_manuale_uso_manutenzione_richiesta_sostituzione boolean not null default false,
  add column if not exists doc_manuale_uso_manutenzione_richiesta_sostituzione_at timestamptz,
  add column if not exists doc_manuale_uso_manutenzione_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists doc_libro_bordo_richiesta_sostituzione boolean not null default false,
  add column if not exists doc_libro_bordo_richiesta_sostituzione_at timestamptz,
  add column if not exists doc_libro_bordo_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null,
  add column if not exists doc_diario_manutenzione_richiesta_sostituzione boolean not null default false,
  add column if not exists doc_diario_manutenzione_richiesta_sostituzione_at timestamptz,
  add column if not exists doc_diario_manutenzione_richiesta_sostituzione_by_user_uuid uuid references public.users(id_uuid) on delete set null;
